<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filedb.proto

namespace Filedb\V1;

use UnexpectedValueException;

/**
 * AggregateOp names a numeric aggregation to compute per group over the request's
 * numeric `field`. COUNT (the per-group record count) is always returned and need
 * not be listed. Any of SUM/AVG/MIN/MAX requires `field` to be set.
 *
 * Protobuf type <code>filedb.v1.AggregateOp</code>
 */
class AggregateOp
{
    /**
     * Generated from protobuf enum <code>AGGREGATE_OP_UNSPECIFIED = 0;</code>
     */
    const AGGREGATE_OP_UNSPECIFIED = 0;
    /**
     * per-group record count (always returned)
     *
     * Generated from protobuf enum <code>AGG_COUNT = 1;</code>
     */
    const AGG_COUNT = 1;
    /**
     * sum of numeric field values
     *
     * Generated from protobuf enum <code>AGG_SUM = 2;</code>
     */
    const AGG_SUM = 2;
    /**
     * mean of numeric field values
     *
     * Generated from protobuf enum <code>AGG_AVG = 3;</code>
     */
    const AGG_AVG = 3;
    /**
     * smallest numeric field value
     *
     * Generated from protobuf enum <code>AGG_MIN = 4;</code>
     */
    const AGG_MIN = 4;
    /**
     * largest numeric field value
     *
     * Generated from protobuf enum <code>AGG_MAX = 5;</code>
     */
    const AGG_MAX = 5;

    private static $valueToName = [
        self::AGGREGATE_OP_UNSPECIFIED => 'AGGREGATE_OP_UNSPECIFIED',
        self::AGG_COUNT => 'AGG_COUNT',
        self::AGG_SUM => 'AGG_SUM',
        self::AGG_AVG => 'AGG_AVG',
        self::AGG_MIN => 'AGG_MIN',
        self::AGG_MAX => 'AGG_MAX',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

