<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filedb.proto

namespace Filedb\V1;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBType;

class CollectionStatsResponse extends \Google\Protobuf\Internal\Message
{
    protected $collection = '';
    protected $record_count = 0;
    protected $segment_count = 0;
    protected $dirty_entries = 0;
    protected $size_bytes = 0;

    public function __construct($data = NULL) {
        \GPBMetadata\Filedb::initOnce();
        parent::__construct($data);
    }

    public function getCollection()
    {
        return $this->collection;
    }

    public function setCollection($var)
    {
        GPBUtil::checkString($var, True);
        $this->collection = $var;
        return $this;
    }

    public function getRecord_count()
    {
        return $this->record_count;
    }

    public function setRecord_count($var)
    {
        GPBUtil::checkUint64($var);
        $this->record_count = $var;
        return $this;
    }

    public function getSegment_count()
    {
        return $this->segment_count;
    }

    public function setSegment_count($var)
    {
        GPBUtil::checkUint64($var);
        $this->segment_count = $var;
        return $this;
    }

    public function getDirty_entries()
    {
        return $this->dirty_entries;
    }

    public function setDirty_entries($var)
    {
        GPBUtil::checkUint64($var);
        $this->dirty_entries = $var;
        return $this;
    }

    public function getSize_bytes()
    {
        return $this->size_bytes;
    }

    public function setSize_bytes($var)
    {
        GPBUtil::checkUint64($var);
        $this->size_bytes = $var;
        return $this;
    }

}
