<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filedb.proto

namespace Filedb\V1;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBType;

class CommitTxRequest extends \Google\Protobuf\Internal\Message
{
    protected $tx_id = '';

    public function __construct($data = NULL) {
        \GPBMetadata\Filedb::initOnce();
        parent::__construct($data);
    }

    public function getTx_id()
    {
        return $this->tx_id;
    }

    public function setTx_id($var)
    {
        GPBUtil::checkString($var, True);
        $this->tx_id = $var;
        return $this;
    }

}
