<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filedb.proto

namespace Filedb\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>filedb.v1.DeleteRequest</code>
 */
class DeleteRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string collection = 1 [json_name = "collection"];</code>
     */
    protected $collection = '';
    /**
     * Generated from protobuf field <code>uint64 id = 2 [json_name = "id"];</code>
     */
    protected $id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $collection
     *     @type int|string $id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Filedb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string collection = 1 [json_name = "collection"];</code>
     * @return string
     */
    public function getCollection()
    {
        return $this->collection;
    }

    /**
     * Generated from protobuf field <code>string collection = 1 [json_name = "collection"];</code>
     * @param string $var
     * @return $this
     */
    public function setCollection($var)
    {
        GPBUtil::checkString($var, True);
        $this->collection = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 2 [json_name = "id"];</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 2 [json_name = "id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

}

