<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filedb.proto

namespace Filedb\V1;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBType;

class EnsureIndexRequest extends \Google\Protobuf\Internal\Message
{
    protected $collection = '';
    protected $field = '';

    public function __construct($data = NULL) {
        \GPBMetadata\Filedb::initOnce();
        parent::__construct($data);
    }

    public function getCollection()
    {
        return $this->collection;
    }

    public function setCollection($var)
    {
        GPBUtil::checkString($var, True);
        $this->collection = $var;
        return $this;
    }

    public function getField()
    {
        return $this->field;
    }

    public function setField($var)
    {
        GPBUtil::checkString($var, True);
        $this->field = $var;
        return $this;
    }

}
