<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filedb.proto

namespace Filedb\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>filedb.v1.FieldFilter</code>
 */
class FieldFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string field = 1 [json_name = "field"];</code>
     */
    protected $field = '';
    /**
     * Generated from protobuf field <code>.filedb.v1.FilterOp op = 2 [json_name = "op"];</code>
     */
    protected $op = 0;
    /**
     * JSON-encoded value for comparison
     *
     * Generated from protobuf field <code>string value = 3 [json_name = "value"];</code>
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $field
     *     @type int $op
     *     @type string $value
     *           JSON-encoded value for comparison
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Filedb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string field = 1 [json_name = "field"];</code>
     * @return string
     */
    public function getField()
    {
        return $this->field;
    }

    /**
     * Generated from protobuf field <code>string field = 1 [json_name = "field"];</code>
     * @param string $var
     * @return $this
     */
    public function setField($var)
    {
        GPBUtil::checkString($var, True);
        $this->field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.filedb.v1.FilterOp op = 2 [json_name = "op"];</code>
     * @return int
     */
    public function getOp()
    {
        return $this->op;
    }

    /**
     * Generated from protobuf field <code>.filedb.v1.FilterOp op = 2 [json_name = "op"];</code>
     * @param int $var
     * @return $this
     */
    public function setOp($var)
    {
        GPBUtil::checkEnum($var, \Filedb\V1\FilterOp::class);
        $this->op = $var;

        return $this;
    }

    /**
     * JSON-encoded value for comparison
     *
     * Generated from protobuf field <code>string value = 3 [json_name = "value"];</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * JSON-encoded value for comparison
     *
     * Generated from protobuf field <code>string value = 3 [json_name = "value"];</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

}

