<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filedb.proto

namespace Filedb\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>filedb.v1.FindResponse</code>
 */
class FindResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.filedb.v1.Record record = 1 [json_name = "record"];</code>
     */
    protected $record = null;
    /**
     * Next-page cursor (N3). Set on the final streamed message when more rows remain
     * under the requested ordering — feed it back as FindRequest.page_token to fetch
     * the next page. Empty on every message means the last page was reached.
     *
     * Generated from protobuf field <code>string page_token = 2 [json_name = "pageToken"];</code>
     */
    protected $page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Filedb\V1\Record $record
     *     @type string $page_token
     *           Next-page cursor (N3). Set on the final streamed message when more rows remain
     *           under the requested ordering — feed it back as FindRequest.page_token to fetch
     *           the next page. Empty on every message means the last page was reached.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Filedb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.filedb.v1.Record record = 1 [json_name = "record"];</code>
     * @return \Filedb\V1\Record|null
     */
    public function getRecord()
    {
        return $this->record;
    }

    public function hasRecord()
    {
        return isset($this->record);
    }

    public function clearRecord()
    {
        unset($this->record);
    }

    /**
     * Generated from protobuf field <code>.filedb.v1.Record record = 1 [json_name = "record"];</code>
     * @param \Filedb\V1\Record $var
     * @return $this
     */
    public function setRecord($var)
    {
        GPBUtil::checkMessage($var, \Filedb\V1\Record::class);
        $this->record = $var;

        return $this;
    }

    /**
     * Next-page cursor (N3). Set on the final streamed message when more rows remain
     * under the requested ordering — feed it back as FindRequest.page_token to fetch
     * the next page. Empty on every message means the last page was reached.
     *
     * Generated from protobuf field <code>string page_token = 2 [json_name = "pageToken"];</code>
     * @return string
     */
    public function getPageToken()
    {
        return $this->page_token;
    }

    /**
     * Next-page cursor (N3). Set on the final streamed message when more rows remain
     * under the requested ordering — feed it back as FindRequest.page_token to fetch
     * the next page. Empty on every message means the last page was reached.
     *
     * Generated from protobuf field <code>string page_token = 2 [json_name = "pageToken"];</code>
     * @param string $var
     * @return $this
     */
    public function setPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_token = $var;

        return $this;
    }

}

