<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filedb.proto

namespace Filedb\V1;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBType;

class FindByIdRequest extends \Google\Protobuf\Internal\Message
{
    protected $collection = '';
    protected $id = 0;

    public function __construct($data = NULL) {
        \GPBMetadata\Filedb::initOnce();
        parent::__construct($data);
    }

    public function getCollection()
    {
        return $this->collection;
    }

    public function setCollection($var)
    {
        GPBUtil::checkString($var, True);
        $this->collection = $var;
        return $this;
    }

    public function getId()
    {
        return $this->id;
    }

    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;
        return $this;
    }

}
