<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filedb.proto

namespace Filedb\V1;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBType;

class InsertManyRequest extends \Google\Protobuf\Internal\Message
{
    protected $collection = '';
    protected $records;

    public function __construct($data = NULL) {
        \GPBMetadata\Filedb::initOnce();
        parent::__construct($data);
    }

    public function getCollection()
    {
        return $this->collection;
    }

    public function setCollection($var)
    {
        GPBUtil::checkString($var, True);
        $this->collection = $var;
        return $this;
    }

    public function getRecords()
    {
        return $this->records;
    }

    public function setRecords($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Struct::class);
        $this->records = $arr;
        return $this;
    }

}
