<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filedb.proto

namespace Filedb\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>filedb.v1.InsertRequest</code>
 */
class InsertRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string collection = 1 [json_name = "collection"];</code>
     */
    protected $collection = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
     */
    protected $data = null;
    /**
     * Optional per-record TTL, in seconds. When > 0, the record expires this long
     * after insertion, overriding any collection default. 0 (the default)
     * applies the collection's default TTL, if any.
     *
     * Generated from protobuf field <code>int64 ttl_seconds = 3 [json_name = "ttlSeconds"];</code>
     */
    protected $ttl_seconds = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $collection
     *     @type \Google\Protobuf\Struct $data
     *     @type int|string $ttl_seconds
     *           Optional per-record TTL, in seconds. When > 0, the record expires this long
     *           after insertion, overriding any collection default. 0 (the default)
     *           applies the collection's default TTL, if any.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Filedb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string collection = 1 [json_name = "collection"];</code>
     * @return string
     */
    public function getCollection()
    {
        return $this->collection;
    }

    /**
     * Generated from protobuf field <code>string collection = 1 [json_name = "collection"];</code>
     * @param string $var
     * @return $this
     */
    public function setCollection($var)
    {
        GPBUtil::checkString($var, True);
        $this->collection = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getData()
    {
        return $this->data;
    }

    public function hasData()
    {
        return isset($this->data);
    }

    public function clearData()
    {
        unset($this->data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->data = $var;

        return $this;
    }

    /**
     * Optional per-record TTL, in seconds. When > 0, the record expires this long
     * after insertion, overriding any collection default. 0 (the default)
     * applies the collection's default TTL, if any.
     *
     * Generated from protobuf field <code>int64 ttl_seconds = 3 [json_name = "ttlSeconds"];</code>
     * @return int|string
     */
    public function getTtlSeconds()
    {
        return $this->ttl_seconds;
    }

    /**
     * Optional per-record TTL, in seconds. When > 0, the record expires this long
     * after insertion, overriding any collection default. 0 (the default)
     * applies the collection's default TTL, if any.
     *
     * Generated from protobuf field <code>int64 ttl_seconds = 3 [json_name = "ttlSeconds"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setTtlSeconds($var)
    {
        GPBUtil::checkInt64($var);
        $this->ttl_seconds = $var;

        return $this;
    }

}

