<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filedb.proto

namespace Filedb\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>filedb.v1.UpdateIfRevResponse</code>
 */
class UpdateIfRevResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * swapped is true when expected_rev matched and the update applied; false —
     * never an error — when the revision was stale or no live record carries key.
     *
     * Generated from protobuf field <code>bool swapped = 1 [json_name = "swapped"];</code>
     */
    protected $swapped = false;
    /**
     * The resulting record when swapped is true; unset otherwise.
     *
     * Generated from protobuf field <code>.filedb.v1.Record record = 2 [json_name = "record"];</code>
     */
    protected $record = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $swapped
     *           swapped is true when expected_rev matched and the update applied; false —
     *           never an error — when the revision was stale or no live record carries key.
     *     @type \Filedb\V1\Record $record
     *           The resulting record when swapped is true; unset otherwise.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Filedb::initOnce();
        parent::__construct($data);
    }

    /**
     * swapped is true when expected_rev matched and the update applied; false —
     * never an error — when the revision was stale or no live record carries key.
     *
     * Generated from protobuf field <code>bool swapped = 1 [json_name = "swapped"];</code>
     * @return bool
     */
    public function getSwapped()
    {
        return $this->swapped;
    }

    /**
     * swapped is true when expected_rev matched and the update applied; false —
     * never an error — when the revision was stale or no live record carries key.
     *
     * Generated from protobuf field <code>bool swapped = 1 [json_name = "swapped"];</code>
     * @param bool $var
     * @return $this
     */
    public function setSwapped($var)
    {
        GPBUtil::checkBool($var);
        $this->swapped = $var;

        return $this;
    }

    /**
     * The resulting record when swapped is true; unset otherwise.
     *
     * Generated from protobuf field <code>.filedb.v1.Record record = 2 [json_name = "record"];</code>
     * @return \Filedb\V1\Record|null
     */
    public function getRecord()
    {
        return $this->record;
    }

    public function hasRecord()
    {
        return isset($this->record);
    }

    public function clearRecord()
    {
        unset($this->record);
    }

    /**
     * The resulting record when swapped is true; unset otherwise.
     *
     * Generated from protobuf field <code>.filedb.v1.Record record = 2 [json_name = "record"];</code>
     * @param \Filedb\V1\Record $var
     * @return $this
     */
    public function setRecord($var)
    {
        GPBUtil::checkMessage($var, \Filedb\V1\Record::class);
        $this->record = $var;

        return $this;
    }

}

