# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import filedb_pb2 as filedb__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in filedb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileDBStub:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    --- Collection management ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCollection = channel.unary_unary(
                '/filedb.v1.FileDB/CreateCollection',
                request_serializer=filedb__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=filedb__pb2.CreateCollectionResponse.FromString,
                _registered_method=True)
        self.DropCollection = channel.unary_unary(
                '/filedb.v1.FileDB/DropCollection',
                request_serializer=filedb__pb2.DropCollectionRequest.SerializeToString,
                response_deserializer=filedb__pb2.DropCollectionResponse.FromString,
                _registered_method=True)
        self.ListCollections = channel.unary_unary(
                '/filedb.v1.FileDB/ListCollections',
                request_serializer=filedb__pb2.ListCollectionsRequest.SerializeToString,
                response_deserializer=filedb__pb2.ListCollectionsResponse.FromString,
                _registered_method=True)
        self.Insert = channel.unary_unary(
                '/filedb.v1.FileDB/Insert',
                request_serializer=filedb__pb2.InsertRequest.SerializeToString,
                response_deserializer=filedb__pb2.InsertResponse.FromString,
                _registered_method=True)
        self.InsertMany = channel.unary_unary(
                '/filedb.v1.FileDB/InsertMany',
                request_serializer=filedb__pb2.InsertManyRequest.SerializeToString,
                response_deserializer=filedb__pb2.InsertManyResponse.FromString,
                _registered_method=True)
        self.FindById = channel.unary_unary(
                '/filedb.v1.FileDB/FindById',
                request_serializer=filedb__pb2.FindByIdRequest.SerializeToString,
                response_deserializer=filedb__pb2.FindResponse.FromString,
                _registered_method=True)
        self.Find = channel.unary_stream(
                '/filedb.v1.FileDB/Find',
                request_serializer=filedb__pb2.FindRequest.SerializeToString,
                response_deserializer=filedb__pb2.FindResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/filedb.v1.FileDB/Update',
                request_serializer=filedb__pb2.UpdateRequest.SerializeToString,
                response_deserializer=filedb__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/filedb.v1.FileDB/Delete',
                request_serializer=filedb__pb2.DeleteRequest.SerializeToString,
                response_deserializer=filedb__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Upsert = channel.unary_unary(
                '/filedb.v1.FileDB/Upsert',
                request_serializer=filedb__pb2.UpsertRequest.SerializeToString,
                response_deserializer=filedb__pb2.UpsertResponse.FromString,
                _registered_method=True)
        self.FindByKey = channel.unary_unary(
                '/filedb.v1.FileDB/FindByKey',
                request_serializer=filedb__pb2.FindByKeyRequest.SerializeToString,
                response_deserializer=filedb__pb2.FindResponse.FromString,
                _registered_method=True)
        self.UpdateByKey = channel.unary_unary(
                '/filedb.v1.FileDB/UpdateByKey',
                request_serializer=filedb__pb2.UpdateByKeyRequest.SerializeToString,
                response_deserializer=filedb__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.DeleteByKey = channel.unary_unary(
                '/filedb.v1.FileDB/DeleteByKey',
                request_serializer=filedb__pb2.DeleteByKeyRequest.SerializeToString,
                response_deserializer=filedb__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.UpdateIfRev = channel.unary_unary(
                '/filedb.v1.FileDB/UpdateIfRev',
                request_serializer=filedb__pb2.UpdateIfRevRequest.SerializeToString,
                response_deserializer=filedb__pb2.UpdateIfRevResponse.FromString,
                _registered_method=True)
        self.EnsureIndex = channel.unary_unary(
                '/filedb.v1.FileDB/EnsureIndex',
                request_serializer=filedb__pb2.EnsureIndexRequest.SerializeToString,
                response_deserializer=filedb__pb2.EnsureIndexResponse.FromString,
                _registered_method=True)
        self.DropIndex = channel.unary_unary(
                '/filedb.v1.FileDB/DropIndex',
                request_serializer=filedb__pb2.DropIndexRequest.SerializeToString,
                response_deserializer=filedb__pb2.DropIndexResponse.FromString,
                _registered_method=True)
        self.ListIndexes = channel.unary_unary(
                '/filedb.v1.FileDB/ListIndexes',
                request_serializer=filedb__pb2.ListIndexesRequest.SerializeToString,
                response_deserializer=filedb__pb2.ListIndexesResponse.FromString,
                _registered_method=True)
        self.BeginTx = channel.unary_unary(
                '/filedb.v1.FileDB/BeginTx',
                request_serializer=filedb__pb2.BeginTxRequest.SerializeToString,
                response_deserializer=filedb__pb2.BeginTxResponse.FromString,
                _registered_method=True)
        self.CommitTx = channel.unary_unary(
                '/filedb.v1.FileDB/CommitTx',
                request_serializer=filedb__pb2.CommitTxRequest.SerializeToString,
                response_deserializer=filedb__pb2.CommitTxResponse.FromString,
                _registered_method=True)
        self.RollbackTx = channel.unary_unary(
                '/filedb.v1.FileDB/RollbackTx',
                request_serializer=filedb__pb2.RollbackTxRequest.SerializeToString,
                response_deserializer=filedb__pb2.RollbackTxResponse.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/filedb.v1.FileDB/Watch',
                request_serializer=filedb__pb2.WatchRequest.SerializeToString,
                response_deserializer=filedb__pb2.WatchEvent.FromString,
                _registered_method=True)
        self.Aggregate = channel.unary_stream(
                '/filedb.v1.FileDB/Aggregate',
                request_serializer=filedb__pb2.AggregateRequest.SerializeToString,
                response_deserializer=filedb__pb2.AggregateResponse.FromString,
                _registered_method=True)
        self.CollectionStats = channel.unary_unary(
                '/filedb.v1.FileDB/CollectionStats',
                request_serializer=filedb__pb2.CollectionStatsRequest.SerializeToString,
                response_deserializer=filedb__pb2.CollectionStatsResponse.FromString,
                _registered_method=True)
        self.Compact = channel.unary_unary(
                '/filedb.v1.FileDB/Compact',
                request_serializer=filedb__pb2.CompactRequest.SerializeToString,
                response_deserializer=filedb__pb2.CompactResponse.FromString,
                _registered_method=True)
        self.Snapshot = channel.unary_stream(
                '/filedb.v1.FileDB/Snapshot',
                request_serializer=filedb__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=filedb__pb2.SnapshotChunk.FromString,
                _registered_method=True)


class FileDBServicer:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    --- Collection management ---
    """

    def CreateCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCollections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Insert(self, request, context):
        """--- CRUD ---

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertMany(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Find(self, request, context):
        """Server-streaming: results are streamed back one by one.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Upsert(self, request, context):
        """--- Keyed CRUD, Upsert & compare-and-swap (N1) ---

        These map straight onto the embedded engine's keyed operations, giving
        network clients natural (caller-supplied) string keys, upsert, and
        optimistic-concurrency updates keyed on a per-record revision (`rev`).

        Upsert inserts data under key if no live record carries it, or replaces the
        existing record's data if one does — atomically. Returns the resulting
        record with its (incremented on replace) revision. This is the keyed-insert
        path: there is no separate InsertWithKey RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindByKey(self, request, context):
        """FindByKey returns the record carrying the caller-supplied string key.
        A missing key yields NOT_FOUND.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateByKey(self, request, context):
        """UpdateByKey overwrites the record carrying key, preserving the key itself.
        A missing key yields NOT_FOUND.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteByKey(self, request, context):
        """DeleteByKey removes the record carrying key. A missing key yields NOT_FOUND.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateIfRev(self, request, context):
        """UpdateIfRev conditionally updates the record carrying key: the write is
        applied only if the record's current revision equals expected_rev. A stale
        revision (or a missing key) is a clean no-op reported as swapped=false, not
        an error.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnsureIndex(self, request, context):
        """--- Secondary indexes ---

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListIndexes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginTx(self, request, context):
        """--- Transactions ---

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitTx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackTx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """--- Watch (server-streaming change feed) ---

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Aggregate(self, request, context):
        """--- Aggregations (N4) ---

        Aggregate computes count and numeric aggregations (sum/avg/min/max) over the
        live records matching the same Filter as Find, optionally grouped by a field.
        It server-streams one message per group; a plain (ungrouped) aggregation
        streams a single message. Aggregation runs entirely in the engine — the
        collection is never materialised on the client.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectionStats(self, request, context):
        """--- Stats ---

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Compact(self, request, context):
        """--- Admin ---

        Compact runs a forced, synchronous compaction pass on a collection and
        returns only after it completes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Snapshot(self, request, context):
        """Snapshot streams a consistent, gzip-compressed tar archive of the whole
        database. Restore by extracting it into a data directory. gRPC-only:
        binary streaming does not map cleanly onto the REST gateway.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=filedb__pb2.CreateCollectionRequest.FromString,
                    response_serializer=filedb__pb2.CreateCollectionResponse.SerializeToString,
            ),
            'DropCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.DropCollection,
                    request_deserializer=filedb__pb2.DropCollectionRequest.FromString,
                    response_serializer=filedb__pb2.DropCollectionResponse.SerializeToString,
            ),
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=filedb__pb2.ListCollectionsRequest.FromString,
                    response_serializer=filedb__pb2.ListCollectionsResponse.SerializeToString,
            ),
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=filedb__pb2.InsertRequest.FromString,
                    response_serializer=filedb__pb2.InsertResponse.SerializeToString,
            ),
            'InsertMany': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertMany,
                    request_deserializer=filedb__pb2.InsertManyRequest.FromString,
                    response_serializer=filedb__pb2.InsertManyResponse.SerializeToString,
            ),
            'FindById': grpc.unary_unary_rpc_method_handler(
                    servicer.FindById,
                    request_deserializer=filedb__pb2.FindByIdRequest.FromString,
                    response_serializer=filedb__pb2.FindResponse.SerializeToString,
            ),
            'Find': grpc.unary_stream_rpc_method_handler(
                    servicer.Find,
                    request_deserializer=filedb__pb2.FindRequest.FromString,
                    response_serializer=filedb__pb2.FindResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=filedb__pb2.UpdateRequest.FromString,
                    response_serializer=filedb__pb2.UpdateResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=filedb__pb2.DeleteRequest.FromString,
                    response_serializer=filedb__pb2.DeleteResponse.SerializeToString,
            ),
            'Upsert': grpc.unary_unary_rpc_method_handler(
                    servicer.Upsert,
                    request_deserializer=filedb__pb2.UpsertRequest.FromString,
                    response_serializer=filedb__pb2.UpsertResponse.SerializeToString,
            ),
            'FindByKey': grpc.unary_unary_rpc_method_handler(
                    servicer.FindByKey,
                    request_deserializer=filedb__pb2.FindByKeyRequest.FromString,
                    response_serializer=filedb__pb2.FindResponse.SerializeToString,
            ),
            'UpdateByKey': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateByKey,
                    request_deserializer=filedb__pb2.UpdateByKeyRequest.FromString,
                    response_serializer=filedb__pb2.UpdateResponse.SerializeToString,
            ),
            'DeleteByKey': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteByKey,
                    request_deserializer=filedb__pb2.DeleteByKeyRequest.FromString,
                    response_serializer=filedb__pb2.DeleteResponse.SerializeToString,
            ),
            'UpdateIfRev': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateIfRev,
                    request_deserializer=filedb__pb2.UpdateIfRevRequest.FromString,
                    response_serializer=filedb__pb2.UpdateIfRevResponse.SerializeToString,
            ),
            'EnsureIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.EnsureIndex,
                    request_deserializer=filedb__pb2.EnsureIndexRequest.FromString,
                    response_serializer=filedb__pb2.EnsureIndexResponse.SerializeToString,
            ),
            'DropIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.DropIndex,
                    request_deserializer=filedb__pb2.DropIndexRequest.FromString,
                    response_serializer=filedb__pb2.DropIndexResponse.SerializeToString,
            ),
            'ListIndexes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListIndexes,
                    request_deserializer=filedb__pb2.ListIndexesRequest.FromString,
                    response_serializer=filedb__pb2.ListIndexesResponse.SerializeToString,
            ),
            'BeginTx': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginTx,
                    request_deserializer=filedb__pb2.BeginTxRequest.FromString,
                    response_serializer=filedb__pb2.BeginTxResponse.SerializeToString,
            ),
            'CommitTx': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitTx,
                    request_deserializer=filedb__pb2.CommitTxRequest.FromString,
                    response_serializer=filedb__pb2.CommitTxResponse.SerializeToString,
            ),
            'RollbackTx': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackTx,
                    request_deserializer=filedb__pb2.RollbackTxRequest.FromString,
                    response_serializer=filedb__pb2.RollbackTxResponse.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=filedb__pb2.WatchRequest.FromString,
                    response_serializer=filedb__pb2.WatchEvent.SerializeToString,
            ),
            'Aggregate': grpc.unary_stream_rpc_method_handler(
                    servicer.Aggregate,
                    request_deserializer=filedb__pb2.AggregateRequest.FromString,
                    response_serializer=filedb__pb2.AggregateResponse.SerializeToString,
            ),
            'CollectionStats': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectionStats,
                    request_deserializer=filedb__pb2.CollectionStatsRequest.FromString,
                    response_serializer=filedb__pb2.CollectionStatsResponse.SerializeToString,
            ),
            'Compact': grpc.unary_unary_rpc_method_handler(
                    servicer.Compact,
                    request_deserializer=filedb__pb2.CompactRequest.FromString,
                    response_serializer=filedb__pb2.CompactResponse.SerializeToString,
            ),
            'Snapshot': grpc.unary_stream_rpc_method_handler(
                    servicer.Snapshot,
                    request_deserializer=filedb__pb2.SnapshotRequest.FromString,
                    response_serializer=filedb__pb2.SnapshotChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'filedb.v1.FileDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('filedb.v1.FileDB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileDB:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    --- Collection management ---
    """

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filedb.v1.FileDB/CreateCollection',
            filedb__pb2.CreateCollectionRequest.SerializeToString,
            filedb__pb2.CreateCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filedb.v1.FileDB/DropCollection',
            filedb__pb2.DropCollectionRequest.SerializeToString,
            filedb__pb2.DropCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filedb.v1.FileDB/ListCollections',
            filedb__pb2.ListCollectionsRequest.SerializeToString,
            filedb__pb2.ListCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filedb.v1.FileDB/Insert',
            filedb__pb2.InsertRequest.SerializeToString,
            filedb__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertMany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filedb.v1.FileDB/InsertMany',
            filedb__pb2.InsertManyRequest.SerializeToString,
            filedb__pb2.InsertManyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filedb.v1.FileDB/FindById',
            filedb__pb2.FindByIdRequest.SerializeToString,
            filedb__pb2.FindResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Find(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/filedb.v1.FileDB/Find',
            filedb__pb2.FindRequest.SerializeToString,
            filedb__pb2.FindResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filedb.v1.FileDB/Update',
            filedb__pb2.UpdateRequest.SerializeToString,
            filedb__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filedb.v1.FileDB/Delete',
            filedb__pb2.DeleteRequest.SerializeToString,
            filedb__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Upsert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filedb.v1.FileDB/Upsert',
            filedb__pb2.UpsertRequest.SerializeToString,
            filedb__pb2.UpsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindByKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filedb.v1.FileDB/FindByKey',
            filedb__pb2.FindByKeyRequest.SerializeToString,
            filedb__pb2.FindResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateByKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filedb.v1.FileDB/UpdateByKey',
            filedb__pb2.UpdateByKeyRequest.SerializeToString,
            filedb__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteByKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filedb.v1.FileDB/DeleteByKey',
            filedb__pb2.DeleteByKeyRequest.SerializeToString,
            filedb__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateIfRev(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filedb.v1.FileDB/UpdateIfRev',
            filedb__pb2.UpdateIfRevRequest.SerializeToString,
            filedb__pb2.UpdateIfRevResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnsureIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filedb.v1.FileDB/EnsureIndex',
            filedb__pb2.EnsureIndexRequest.SerializeToString,
            filedb__pb2.EnsureIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filedb.v1.FileDB/DropIndex',
            filedb__pb2.DropIndexRequest.SerializeToString,
            filedb__pb2.DropIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListIndexes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filedb.v1.FileDB/ListIndexes',
            filedb__pb2.ListIndexesRequest.SerializeToString,
            filedb__pb2.ListIndexesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BeginTx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filedb.v1.FileDB/BeginTx',
            filedb__pb2.BeginTxRequest.SerializeToString,
            filedb__pb2.BeginTxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitTx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filedb.v1.FileDB/CommitTx',
            filedb__pb2.CommitTxRequest.SerializeToString,
            filedb__pb2.CommitTxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackTx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filedb.v1.FileDB/RollbackTx',
            filedb__pb2.RollbackTxRequest.SerializeToString,
            filedb__pb2.RollbackTxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/filedb.v1.FileDB/Watch',
            filedb__pb2.WatchRequest.SerializeToString,
            filedb__pb2.WatchEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Aggregate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/filedb.v1.FileDB/Aggregate',
            filedb__pb2.AggregateRequest.SerializeToString,
            filedb__pb2.AggregateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectionStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filedb.v1.FileDB/CollectionStats',
            filedb__pb2.CollectionStatsRequest.SerializeToString,
            filedb__pb2.CollectionStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Compact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filedb.v1.FileDB/Compact',
            filedb__pb2.CompactRequest.SerializeToString,
            filedb__pb2.CompactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Snapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/filedb.v1.FileDB/Snapshot',
            filedb__pb2.SnapshotRequest.SerializeToString,
            filedb__pb2.SnapshotChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
