# Generated by the protocol buffer compiler. DO NOT EDIT!
# source: filedb.proto

require "google/protobuf"
require "google/protobuf/struct_pb"
require "google/protobuf/timestamp_pb"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("filedb.proto", syntax: :proto3) do
    add_message "filedb.v1.Record" do
      optional :id,            :uint64,  1
      optional :data,          :message, 2, "google.protobuf.Struct"
      optional :date_added,    :message, 3, "google.protobuf.Timestamp"
      optional :date_modified, :message, 4, "google.protobuf.Timestamp"
    end
    add_message "filedb.v1.Filter" do
      oneof :kind do
        optional :field, :message, 1, "filedb.v1.FieldFilter"
        optional :and,   :message, 2, "filedb.v1.AndFilter"
        optional :or,    :message, 3, "filedb.v1.OrFilter"
      end
    end
    add_message "filedb.v1.FieldFilter" do
      optional :field, :string, 1
      optional :op,    :enum,   2, "filedb.v1.FilterOp"
      optional :value, :string, 3
    end
    add_message "filedb.v1.AndFilter" do
      repeated :filters, :message, 1, "filedb.v1.Filter"
    end
    add_message "filedb.v1.OrFilter" do
      repeated :filters, :message, 1, "filedb.v1.Filter"
    end
    add_message "filedb.v1.CreateCollectionRequest" do
      optional :name, :string, 1
    end
    add_message "filedb.v1.CreateCollectionResponse" do
      optional :name,       :string, 1
      optional :created_at, :string, 2
    end
    add_message "filedb.v1.DropCollectionRequest" do
      optional :name, :string, 1
    end
    add_message "filedb.v1.DropCollectionResponse" do
      optional :ok, :bool, 1
    end
    add_message "filedb.v1.ListCollectionsRequest" do
    end
    add_message "filedb.v1.ListCollectionsResponse" do
      repeated :names, :string, 1
    end
    add_message "filedb.v1.InsertRequest" do
      optional :collection, :string,  1
      optional :data,       :message, 2, "google.protobuf.Struct"
    end
    add_message "filedb.v1.InsertResponse" do
      optional :id,         :uint64, 1
      optional :date_added, :string, 2
    end
    add_message "filedb.v1.InsertManyRequest" do
      optional :collection, :string,  1
      repeated :records,    :message, 2, "google.protobuf.Struct"
    end
    add_message "filedb.v1.InsertManyResponse" do
      repeated :ids, :uint64, 1
    end
    add_message "filedb.v1.FindByIdRequest" do
      optional :collection, :string, 1
      optional :id,         :uint64, 2
    end
    add_message "filedb.v1.FindRequest" do
      optional :collection, :string,  1
      optional :filter,     :message, 2, "filedb.v1.Filter"
      optional :limit,      :uint32,  3
      optional :offset,     :uint32,  4
      optional :order_by,   :string,  5
      optional :descending, :bool,    6
    end
    add_message "filedb.v1.FindResponse" do
      optional :record, :message, 1, "filedb.v1.Record"
    end
    add_message "filedb.v1.UpdateRequest" do
      optional :collection, :string,  1
      optional :id,         :uint64,  2
      optional :data,       :message, 3, "google.protobuf.Struct"
    end
    add_message "filedb.v1.UpdateResponse" do
      optional :id,            :uint64, 1
      optional :date_modified, :string, 2
    end
    add_message "filedb.v1.DeleteRequest" do
      optional :collection, :string, 1
      optional :id,         :uint64, 2
    end
    add_message "filedb.v1.DeleteResponse" do
      optional :ok, :bool, 1
    end
    add_message "filedb.v1.EnsureIndexRequest" do
      optional :collection, :string, 1
      optional :field,      :string, 2
    end
    add_message "filedb.v1.EnsureIndexResponse" do
      optional :collection, :string, 1
      optional :field,      :string, 2
    end
    add_message "filedb.v1.DropIndexRequest" do
      optional :collection, :string, 1
      optional :field,      :string, 2
    end
    add_message "filedb.v1.DropIndexResponse" do
      optional :ok, :bool, 1
    end
    add_message "filedb.v1.ListIndexesRequest" do
      optional :collection, :string, 1
    end
    add_message "filedb.v1.ListIndexesResponse" do
      repeated :fields, :string, 1
    end
    add_message "filedb.v1.BeginTxRequest" do
      optional :collection, :string, 1
    end
    add_message "filedb.v1.BeginTxResponse" do
      optional :tx_id, :string, 1
    end
    add_message "filedb.v1.CommitTxRequest" do
      optional :tx_id, :string, 1
    end
    add_message "filedb.v1.CommitTxResponse" do
      optional :ok, :bool, 1
    end
    add_message "filedb.v1.RollbackTxRequest" do
      optional :tx_id, :string, 1
    end
    add_message "filedb.v1.RollbackTxResponse" do
      optional :ok, :bool, 1
    end
    add_message "filedb.v1.WatchRequest" do
      optional :collection, :string,  1
      optional :filter,     :message, 2, "filedb.v1.Filter"
    end
    add_message "filedb.v1.WatchEvent" do
      optional :op,         :enum,    1, "filedb.v1.WatchOp"
      optional :collection, :string,  2
      optional :record,     :message, 3, "filedb.v1.Record"
      optional :ts,         :message, 4, "google.protobuf.Timestamp"
    end
    add_message "filedb.v1.CollectionStatsRequest" do
      optional :collection, :string, 1
    end
    add_message "filedb.v1.CollectionStatsResponse" do
      optional :collection,    :string, 1
      optional :record_count,  :uint64, 2
      optional :segment_count, :uint64, 3
      optional :dirty_entries, :uint64, 4
      optional :size_bytes,    :uint64, 5
    end
    add_enum "filedb.v1.FilterOp" do
      value :FILTER_OP_UNSPECIFIED, 0
      value :EQ,       1
      value :NEQ,      2
      value :GT,       3
      value :GTE,      4
      value :LT,       5
      value :LTE,      6
      value :CONTAINS, 7
      value :REGEX,    8
    end
    add_enum "filedb.v1.WatchOp" do
      value :WATCH_OP_UNSPECIFIED, 0
      value :INSERTED, 1
      value :UPDATED,  2
      value :DELETED,  3
    end
  end
end

module Filedb
  module V1
    Record                   = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.Record").msgclass
    Filter                   = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.Filter").msgclass
    FieldFilter              = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.FieldFilter").msgclass
    AndFilter                = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.AndFilter").msgclass
    OrFilter                 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.OrFilter").msgclass
    CreateCollectionRequest  = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.CreateCollectionRequest").msgclass
    CreateCollectionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.CreateCollectionResponse").msgclass
    DropCollectionRequest    = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.DropCollectionRequest").msgclass
    DropCollectionResponse   = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.DropCollectionResponse").msgclass
    ListCollectionsRequest   = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.ListCollectionsRequest").msgclass
    ListCollectionsResponse  = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.ListCollectionsResponse").msgclass
    InsertRequest            = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.InsertRequest").msgclass
    InsertResponse           = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.InsertResponse").msgclass
    InsertManyRequest        = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.InsertManyRequest").msgclass
    InsertManyResponse       = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.InsertManyResponse").msgclass
    FindByIdRequest          = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.FindByIdRequest").msgclass
    FindRequest              = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.FindRequest").msgclass
    FindResponse             = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.FindResponse").msgclass
    UpdateRequest            = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.UpdateRequest").msgclass
    UpdateResponse           = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.UpdateResponse").msgclass
    DeleteRequest            = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.DeleteRequest").msgclass
    DeleteResponse           = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.DeleteResponse").msgclass
    EnsureIndexRequest       = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.EnsureIndexRequest").msgclass
    EnsureIndexResponse      = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.EnsureIndexResponse").msgclass
    DropIndexRequest         = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.DropIndexRequest").msgclass
    DropIndexResponse        = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.DropIndexResponse").msgclass
    ListIndexesRequest       = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.ListIndexesRequest").msgclass
    ListIndexesResponse      = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.ListIndexesResponse").msgclass
    BeginTxRequest           = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.BeginTxRequest").msgclass
    BeginTxResponse          = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.BeginTxResponse").msgclass
    CommitTxRequest          = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.CommitTxRequest").msgclass
    CommitTxResponse         = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.CommitTxResponse").msgclass
    RollbackTxRequest        = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.RollbackTxRequest").msgclass
    RollbackTxResponse       = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.RollbackTxResponse").msgclass
    WatchRequest             = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.WatchRequest").msgclass
    WatchEvent               = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.WatchEvent").msgclass
    CollectionStatsRequest   = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.CollectionStatsRequest").msgclass
    CollectionStatsResponse  = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.CollectionStatsResponse").msgclass
    FilterOp                 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.FilterOp").enummodule
    WatchOp                  = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filedb.v1.WatchOp").enummodule
  end
end
