// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/filedb.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterOp int32

const (
	FilterOp_FILTER_OP_UNSPECIFIED FilterOp = 0
	FilterOp_EQ                    FilterOp = 1 // equal
	FilterOp_NEQ                   FilterOp = 2 // not equal
	FilterOp_GT                    FilterOp = 3 // greater than
	FilterOp_GTE                   FilterOp = 4 // greater than or equal
	FilterOp_LT                    FilterOp = 5 // less than
	FilterOp_LTE                   FilterOp = 6 // less than or equal
	FilterOp_CONTAINS              FilterOp = 7 // string contains
	FilterOp_REGEX                 FilterOp = 8 // regular expression match
)

// Enum value maps for FilterOp.
var (
	FilterOp_name = map[int32]string{
		0: "FILTER_OP_UNSPECIFIED",
		1: "EQ",
		2: "NEQ",
		3: "GT",
		4: "GTE",
		5: "LT",
		6: "LTE",
		7: "CONTAINS",
		8: "REGEX",
	}
	FilterOp_value = map[string]int32{
		"FILTER_OP_UNSPECIFIED": 0,
		"EQ":                    1,
		"NEQ":                   2,
		"GT":                    3,
		"GTE":                   4,
		"LT":                    5,
		"LTE":                   6,
		"CONTAINS":              7,
		"REGEX":                 8,
	}
)

func (x FilterOp) Enum() *FilterOp {
	p := new(FilterOp)
	*p = x
	return p
}

func (x FilterOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterOp) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_filedb_proto_enumTypes[0].Descriptor()
}

func (FilterOp) Type() protoreflect.EnumType {
	return &file_proto_filedb_proto_enumTypes[0]
}

func (x FilterOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterOp.Descriptor instead.
func (FilterOp) EnumDescriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{0}
}

type WatchOp int32

const (
	WatchOp_WATCH_OP_UNSPECIFIED WatchOp = 0
	WatchOp_INSERTED             WatchOp = 1
	WatchOp_UPDATED              WatchOp = 2
	WatchOp_DELETED              WatchOp = 3
	// OVERFLOW signals that the server dropped events because this subscriber
	// fell behind. The client missed writes and should resync. No record is set.
	WatchOp_OVERFLOW WatchOp = 4
)

// Enum value maps for WatchOp.
var (
	WatchOp_name = map[int32]string{
		0: "WATCH_OP_UNSPECIFIED",
		1: "INSERTED",
		2: "UPDATED",
		3: "DELETED",
		4: "OVERFLOW",
	}
	WatchOp_value = map[string]int32{
		"WATCH_OP_UNSPECIFIED": 0,
		"INSERTED":             1,
		"UPDATED":              2,
		"DELETED":              3,
		"OVERFLOW":             4,
	}
)

func (x WatchOp) Enum() *WatchOp {
	p := new(WatchOp)
	*p = x
	return p
}

func (x WatchOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchOp) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_filedb_proto_enumTypes[1].Descriptor()
}

func (WatchOp) Type() protoreflect.EnumType {
	return &file_proto_filedb_proto_enumTypes[1]
}

func (x WatchOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchOp.Descriptor instead.
func (WatchOp) EnumDescriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{1}
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	DateAdded     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date_added,json=dateAdded,proto3" json:"date_added,omitempty"`
	DateModified  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date_modified,json=dateModified,proto3" json:"date_modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_proto_filedb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Record) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Record) GetDateAdded() *timestamppb.Timestamp {
	if x != nil {
		return x.DateAdded
	}
	return nil
}

func (x *Record) GetDateModified() *timestamppb.Timestamp {
	if x != nil {
		return x.DateModified
	}
	return nil
}

// A composable filter node.
type Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Filter_Field
	//	*Filter_And
	//	*Filter_Or
	Kind          isFilter_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_proto_filedb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{1}
}

func (x *Filter) GetKind() isFilter_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Filter) GetField() *FieldFilter {
	if x != nil {
		if x, ok := x.Kind.(*Filter_Field); ok {
			return x.Field
		}
	}
	return nil
}

func (x *Filter) GetAnd() *AndFilter {
	if x != nil {
		if x, ok := x.Kind.(*Filter_And); ok {
			return x.And
		}
	}
	return nil
}

func (x *Filter) GetOr() *OrFilter {
	if x != nil {
		if x, ok := x.Kind.(*Filter_Or); ok {
			return x.Or
		}
	}
	return nil
}

type isFilter_Kind interface {
	isFilter_Kind()
}

type Filter_Field struct {
	Field *FieldFilter `protobuf:"bytes,1,opt,name=field,proto3,oneof"`
}

type Filter_And struct {
	And *AndFilter `protobuf:"bytes,2,opt,name=and,proto3,oneof"`
}

type Filter_Or struct {
	Or *OrFilter `protobuf:"bytes,3,opt,name=or,proto3,oneof"`
}

func (*Filter_Field) isFilter_Kind() {}

func (*Filter_And) isFilter_Kind() {}

func (*Filter_Or) isFilter_Kind() {}

type FieldFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Op            FilterOp               `protobuf:"varint,2,opt,name=op,proto3,enum=filedb.v1.FilterOp" json:"op,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"` // JSON-encoded value for comparison
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldFilter) Reset() {
	*x = FieldFilter{}
	mi := &file_proto_filedb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldFilter) ProtoMessage() {}

func (x *FieldFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldFilter.ProtoReflect.Descriptor instead.
func (*FieldFilter) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{2}
}

func (x *FieldFilter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldFilter) GetOp() FilterOp {
	if x != nil {
		return x.Op
	}
	return FilterOp_FILTER_OP_UNSPECIFIED
}

func (x *FieldFilter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AndFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*Filter              `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AndFilter) Reset() {
	*x = AndFilter{}
	mi := &file_proto_filedb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AndFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AndFilter) ProtoMessage() {}

func (x *AndFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AndFilter.ProtoReflect.Descriptor instead.
func (*AndFilter) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{3}
}

func (x *AndFilter) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type OrFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*Filter              `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrFilter) Reset() {
	*x = OrFilter{}
	mi := &file_proto_filedb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrFilter) ProtoMessage() {}

func (x *OrFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrFilter.ProtoReflect.Descriptor instead.
func (*OrFilter) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{4}
}

func (x *OrFilter) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type CreateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_proto_filedb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionResponse) Reset() {
	*x = CreateCollectionResponse{}
	mi := &file_proto_filedb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionResponse) ProtoMessage() {}

func (x *CreateCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionResponse.ProtoReflect.Descriptor instead.
func (*CreateCollectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCollectionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCollectionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type DropCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropCollectionRequest) Reset() {
	*x = DropCollectionRequest{}
	mi := &file_proto_filedb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropCollectionRequest) ProtoMessage() {}

func (x *DropCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropCollectionRequest.ProtoReflect.Descriptor instead.
func (*DropCollectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{7}
}

func (x *DropCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DropCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropCollectionResponse) Reset() {
	*x = DropCollectionResponse{}
	mi := &file_proto_filedb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropCollectionResponse) ProtoMessage() {}

func (x *DropCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropCollectionResponse.ProtoReflect.Descriptor instead.
func (*DropCollectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{8}
}

func (x *DropCollectionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListCollectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_proto_filedb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{9}
}

type ListCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_proto_filedb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{10}
}

func (x *ListCollectionsResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_proto_filedb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{11}
}

func (x *InsertRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *InsertRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DateAdded     string                 `protobuf:"bytes,2,opt,name=date_added,json=dateAdded,proto3" json:"date_added,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_proto_filedb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{12}
}

func (x *InsertResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InsertResponse) GetDateAdded() string {
	if x != nil {
		return x.DateAdded
	}
	return ""
}

type InsertManyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Records       []*structpb.Struct     `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertManyRequest) Reset() {
	*x = InsertManyRequest{}
	mi := &file_proto_filedb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertManyRequest) ProtoMessage() {}

func (x *InsertManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertManyRequest.ProtoReflect.Descriptor instead.
func (*InsertManyRequest) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{13}
}

func (x *InsertManyRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *InsertManyRequest) GetRecords() []*structpb.Struct {
	if x != nil {
		return x.Records
	}
	return nil
}

type InsertManyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertManyResponse) Reset() {
	*x = InsertManyResponse{}
	mi := &file_proto_filedb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertManyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertManyResponse) ProtoMessage() {}

func (x *InsertManyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertManyResponse.ProtoReflect.Descriptor instead.
func (*InsertManyResponse) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{14}
}

func (x *InsertManyResponse) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type FindByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdRequest) Reset() {
	*x = FindByIdRequest{}
	mi := &file_proto_filedb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdRequest) ProtoMessage() {}

func (x *FindByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdRequest.ProtoReflect.Descriptor instead.
func (*FindByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{15}
}

func (x *FindByIdRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *FindByIdRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Filter        *Filter                `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` // 0 = no limit
	Offset        uint32                 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	OrderBy       string                 `protobuf:"bytes,5,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"` // field name
	Descending    bool                   `protobuf:"varint,6,opt,name=descending,proto3" json:"descending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRequest) Reset() {
	*x = FindRequest{}
	mi := &file_proto_filedb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRequest) ProtoMessage() {}

func (x *FindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRequest.ProtoReflect.Descriptor instead.
func (*FindRequest) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{16}
}

func (x *FindRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *FindRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *FindRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FindRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FindRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *FindRequest) GetDescending() bool {
	if x != nil {
		return x.Descending
	}
	return false
}

type FindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindResponse) Reset() {
	*x = FindResponse{}
	mi := &file_proto_filedb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindResponse) ProtoMessage() {}

func (x *FindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindResponse.ProtoReflect.Descriptor instead.
func (*FindResponse) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{17}
}

func (x *FindResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_proto_filedb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *UpdateRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DateModified  string                 `protobuf:"bytes,2,opt,name=date_modified,json=dateModified,proto3" json:"date_modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_proto_filedb_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateResponse) GetDateModified() string {
	if x != nil {
		return x.DateModified
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_filedb_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DeleteRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_filedb_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type EnsureIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureIndexRequest) Reset() {
	*x = EnsureIndexRequest{}
	mi := &file_proto_filedb_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureIndexRequest) ProtoMessage() {}

func (x *EnsureIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureIndexRequest.ProtoReflect.Descriptor instead.
func (*EnsureIndexRequest) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{22}
}

func (x *EnsureIndexRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *EnsureIndexRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type EnsureIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureIndexResponse) Reset() {
	*x = EnsureIndexResponse{}
	mi := &file_proto_filedb_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureIndexResponse) ProtoMessage() {}

func (x *EnsureIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureIndexResponse.ProtoReflect.Descriptor instead.
func (*EnsureIndexResponse) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{23}
}

func (x *EnsureIndexResponse) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *EnsureIndexResponse) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type DropIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropIndexRequest) Reset() {
	*x = DropIndexRequest{}
	mi := &file_proto_filedb_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropIndexRequest) ProtoMessage() {}

func (x *DropIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropIndexRequest.ProtoReflect.Descriptor instead.
func (*DropIndexRequest) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{24}
}

func (x *DropIndexRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DropIndexRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type DropIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropIndexResponse) Reset() {
	*x = DropIndexResponse{}
	mi := &file_proto_filedb_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropIndexResponse) ProtoMessage() {}

func (x *DropIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropIndexResponse.ProtoReflect.Descriptor instead.
func (*DropIndexResponse) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{25}
}

func (x *DropIndexResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListIndexesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIndexesRequest) Reset() {
	*x = ListIndexesRequest{}
	mi := &file_proto_filedb_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIndexesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIndexesRequest) ProtoMessage() {}

func (x *ListIndexesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIndexesRequest.ProtoReflect.Descriptor instead.
func (*ListIndexesRequest) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{26}
}

func (x *ListIndexesRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type ListIndexesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []string               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIndexesResponse) Reset() {
	*x = ListIndexesResponse{}
	mi := &file_proto_filedb_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIndexesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIndexesResponse) ProtoMessage() {}

func (x *ListIndexesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIndexesResponse.ProtoReflect.Descriptor instead.
func (*ListIndexesResponse) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{27}
}

func (x *ListIndexesResponse) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type BeginTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginTxRequest) Reset() {
	*x = BeginTxRequest{}
	mi := &file_proto_filedb_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTxRequest) ProtoMessage() {}

func (x *BeginTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTxRequest.ProtoReflect.Descriptor instead.
func (*BeginTxRequest) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{28}
}

func (x *BeginTxRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type BeginTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginTxResponse) Reset() {
	*x = BeginTxResponse{}
	mi := &file_proto_filedb_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTxResponse) ProtoMessage() {}

func (x *BeginTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTxResponse.ProtoReflect.Descriptor instead.
func (*BeginTxResponse) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{29}
}

func (x *BeginTxResponse) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type CommitTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitTxRequest) Reset() {
	*x = CommitTxRequest{}
	mi := &file_proto_filedb_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTxRequest) ProtoMessage() {}

func (x *CommitTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTxRequest.ProtoReflect.Descriptor instead.
func (*CommitTxRequest) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{30}
}

func (x *CommitTxRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type CommitTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitTxResponse) Reset() {
	*x = CommitTxResponse{}
	mi := &file_proto_filedb_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTxResponse) ProtoMessage() {}

func (x *CommitTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTxResponse.ProtoReflect.Descriptor instead.
func (*CommitTxResponse) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{31}
}

func (x *CommitTxResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RollbackTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackTxRequest) Reset() {
	*x = RollbackTxRequest{}
	mi := &file_proto_filedb_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackTxRequest) ProtoMessage() {}

func (x *RollbackTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackTxRequest.ProtoReflect.Descriptor instead.
func (*RollbackTxRequest) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{32}
}

func (x *RollbackTxRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type RollbackTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackTxResponse) Reset() {
	*x = RollbackTxResponse{}
	mi := &file_proto_filedb_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackTxResponse) ProtoMessage() {}

func (x *RollbackTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackTxResponse.ProtoReflect.Descriptor instead.
func (*RollbackTxResponse) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{33}
}

func (x *RollbackTxResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Filter        *Filter                `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"` // optional: only receive events matching this filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_proto_filedb_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{34}
}

func (x *WatchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *WatchRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type WatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            WatchOp                `protobuf:"varint,1,opt,name=op,proto3,enum=filedb.v1.WatchOp" json:"op,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Record        *Record                `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_proto_filedb_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{35}
}

func (x *WatchEvent) GetOp() WatchOp {
	if x != nil {
		return x.Op
	}
	return WatchOp_WATCH_OP_UNSPECIFIED
}

func (x *WatchEvent) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *WatchEvent) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *WatchEvent) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

type CollectionStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionStatsRequest) Reset() {
	*x = CollectionStatsRequest{}
	mi := &file_proto_filedb_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionStatsRequest) ProtoMessage() {}

func (x *CollectionStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionStatsRequest.ProtoReflect.Descriptor instead.
func (*CollectionStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{36}
}

func (x *CollectionStatsRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type CollectionStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	RecordCount   uint64                 `protobuf:"varint,2,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	SegmentCount  uint64                 `protobuf:"varint,3,opt,name=segment_count,json=segmentCount,proto3" json:"segment_count,omitempty"`
	DirtyEntries  uint64                 `protobuf:"varint,4,opt,name=dirty_entries,json=dirtyEntries,proto3" json:"dirty_entries,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionStatsResponse) Reset() {
	*x = CollectionStatsResponse{}
	mi := &file_proto_filedb_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionStatsResponse) ProtoMessage() {}

func (x *CollectionStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filedb_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionStatsResponse.ProtoReflect.Descriptor instead.
func (*CollectionStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_filedb_proto_rawDescGZIP(), []int{37}
}

func (x *CollectionStatsResponse) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *CollectionStatsResponse) GetRecordCount() uint64 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *CollectionStatsResponse) GetSegmentCount() uint64 {
	if x != nil {
		return x.SegmentCount
	}
	return 0
}

func (x *CollectionStatsResponse) GetDirtyEntries() uint64 {
	if x != nil {
		return x.DirtyEntries
	}
	return 0
}

func (x *CollectionStatsResponse) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

var File_proto_filedb_proto protoreflect.FileDescriptor

const file_proto_filedb_proto_rawDesc = "" +
	"\n" +
	"\x12proto/filedb.proto\x12\tfiledb.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xc1\x01\n" +
	"\x06Record\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\x129\n" +
	"\n" +
	"date_added\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tdateAdded\x12?\n" +
	"\rdate_modified\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fdateModified\"\x91\x01\n" +
	"\x06Filter\x12.\n" +
	"\x05field\x18\x01 \x01(\v2\x16.filedb.v1.FieldFilterH\x00R\x05field\x12(\n" +
	"\x03and\x18\x02 \x01(\v2\x14.filedb.v1.AndFilterH\x00R\x03and\x12%\n" +
	"\x02or\x18\x03 \x01(\v2\x13.filedb.v1.OrFilterH\x00R\x02orB\x06\n" +
	"\x04kind\"^\n" +
	"\vFieldFilter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12#\n" +
	"\x02op\x18\x02 \x01(\x0e2\x13.filedb.v1.FilterOpR\x02op\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"8\n" +
	"\tAndFilter\x12+\n" +
	"\afilters\x18\x01 \x03(\v2\x11.filedb.v1.FilterR\afilters\"7\n" +
	"\bOrFilter\x12+\n" +
	"\afilters\x18\x01 \x03(\v2\x11.filedb.v1.FilterR\afilters\"-\n" +
	"\x17CreateCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"M\n" +
	"\x18CreateCollectionResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\"+\n" +
	"\x15DropCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"(\n" +
	"\x16DropCollectionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x18\n" +
	"\x16ListCollectionsRequest\"/\n" +
	"\x17ListCollectionsResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"\\\n" +
	"\rInsertRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\"?\n" +
	"\x0eInsertResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"date_added\x18\x02 \x01(\tR\tdateAdded\"f\n" +
	"\x11InsertManyRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x121\n" +
	"\arecords\x18\x02 \x03(\v2\x17.google.protobuf.StructR\arecords\"&\n" +
	"\x12InsertManyResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\"A\n" +
	"\x0fFindByIdRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\"\xc1\x01\n" +
	"\vFindRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12)\n" +
	"\x06filter\x18\x02 \x01(\v2\x11.filedb.v1.FilterR\x06filter\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\rR\x06offset\x12\x19\n" +
	"\border_by\x18\x05 \x01(\tR\aorderBy\x12\x1e\n" +
	"\n" +
	"descending\x18\x06 \x01(\bR\n" +
	"descending\"9\n" +
	"\fFindResponse\x12)\n" +
	"\x06record\x18\x01 \x01(\v2\x11.filedb.v1.RecordR\x06record\"l\n" +
	"\rUpdateRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\"E\n" +
	"\x0eUpdateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12#\n" +
	"\rdate_modified\x18\x02 \x01(\tR\fdateModified\"?\n" +
	"\rDeleteRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\" \n" +
	"\x0eDeleteResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"J\n" +
	"\x12EnsureIndexRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\"K\n" +
	"\x13EnsureIndexResponse\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\"H\n" +
	"\x10DropIndexRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\"#\n" +
	"\x11DropIndexResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"4\n" +
	"\x12ListIndexesRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\"-\n" +
	"\x13ListIndexesResponse\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fields\"0\n" +
	"\x0eBeginTxRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\"&\n" +
	"\x0fBeginTxResponse\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\"&\n" +
	"\x0fCommitTxRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\"\"\n" +
	"\x10CommitTxResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"(\n" +
	"\x11RollbackTxRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\"$\n" +
	"\x12RollbackTxResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"Y\n" +
	"\fWatchRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12)\n" +
	"\x06filter\x18\x02 \x01(\v2\x11.filedb.v1.FilterR\x06filter\"\xa7\x01\n" +
	"\n" +
	"WatchEvent\x12\"\n" +
	"\x02op\x18\x01 \x01(\x0e2\x12.filedb.v1.WatchOpR\x02op\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12)\n" +
	"\x06record\x18\x03 \x01(\v2\x11.filedb.v1.RecordR\x06record\x12*\n" +
	"\x02ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\"8\n" +
	"\x16CollectionStatsRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\"\xc5\x01\n" +
	"\x17CollectionStatsResponse\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12!\n" +
	"\frecord_count\x18\x02 \x01(\x04R\vrecordCount\x12#\n" +
	"\rsegment_count\x18\x03 \x01(\x04R\fsegmentCount\x12#\n" +
	"\rdirty_entries\x18\x04 \x01(\x04R\fdirtyEntries\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x04R\tsizeBytes*q\n" +
	"\bFilterOp\x12\x19\n" +
	"\x15FILTER_OP_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02EQ\x10\x01\x12\a\n" +
	"\x03NEQ\x10\x02\x12\x06\n" +
	"\x02GT\x10\x03\x12\a\n" +
	"\x03GTE\x10\x04\x12\x06\n" +
	"\x02LT\x10\x05\x12\a\n" +
	"\x03LTE\x10\x06\x12\f\n" +
	"\bCONTAINS\x10\a\x12\t\n" +
	"\x05REGEX\x10\b*Y\n" +
	"\aWatchOp\x12\x18\n" +
	"\x14WATCH_OP_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bINSERTED\x10\x01\x12\v\n" +
	"\aUPDATED\x10\x02\x12\v\n" +
	"\aDELETED\x10\x03\x12\f\n" +
	"\bOVERFLOW\x10\x042\xe0\r\n" +
	"\x06FileDB\x12w\n" +
	"\x10CreateCollection\x12\".filedb.v1.CreateCollectionRequest\x1a#.filedb.v1.CreateCollectionResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/collections\x12u\n" +
	"\x0eDropCollection\x12 .filedb.v1.DropCollectionRequest\x1a!.filedb.v1.DropCollectionResponse\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/v1/collections/{name}\x12q\n" +
	"\x0fListCollections\x12!.filedb.v1.ListCollectionsRequest\x1a\".filedb.v1.ListCollectionsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/collections\x12b\n" +
	"\x06Insert\x12\x18.filedb.v1.InsertRequest\x1a\x19.filedb.v1.InsertResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/{collection}/records\x12t\n" +
	"\n" +
	"InsertMany\x12\x1c.filedb.v1.InsertManyRequest\x1a\x1d.filedb.v1.InsertManyResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/{collection}/records/batch\x12f\n" +
	"\bFindById\x12\x1a.filedb.v1.FindByIdRequest\x1a\x17.filedb.v1.FindResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/{collection}/records/{id}\x12c\n" +
	"\x04Find\x12\x16.filedb.v1.FindRequest\x1a\x17.filedb.v1.FindResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/{collection}/records/find0\x01\x12g\n" +
	"\x06Update\x12\x18.filedb.v1.UpdateRequest\x1a\x19.filedb.v1.UpdateResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\x1a\x1d/v1/{collection}/records/{id}\x12d\n" +
	"\x06Delete\x12\x18.filedb.v1.DeleteRequest\x1a\x19.filedb.v1.DeleteResponse\"%\x82\xd3\xe4\x93\x02\x1f*\x1d/v1/{collection}/records/{id}\x12q\n" +
	"\vEnsureIndex\x12\x1d.filedb.v1.EnsureIndexRequest\x1a\x1e.filedb.v1.EnsureIndexResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/{collection}/indexes\x12p\n" +
	"\tDropIndex\x12\x1b.filedb.v1.DropIndexRequest\x1a\x1c.filedb.v1.DropIndexResponse\"(\x82\xd3\xe4\x93\x02\"* /v1/{collection}/indexes/{field}\x12n\n" +
	"\vListIndexes\x12\x1d.filedb.v1.ListIndexesRequest\x1a\x1e.filedb.v1.ListIndexesResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/{collection}/indexes\x12@\n" +
	"\aBeginTx\x12\x19.filedb.v1.BeginTxRequest\x1a\x1a.filedb.v1.BeginTxResponse\x12C\n" +
	"\bCommitTx\x12\x1a.filedb.v1.CommitTxRequest\x1a\x1b.filedb.v1.CommitTxResponse\x12I\n" +
	"\n" +
	"RollbackTx\x12\x1c.filedb.v1.RollbackTxRequest\x1a\x1d.filedb.v1.RollbackTxResponse\x12\\\n" +
	"\x05Watch\x12\x17.filedb.v1.WatchRequest\x1a\x15.filedb.v1.WatchEvent\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/{collection}/watch0\x01\x12x\n" +
	"\x0fCollectionStats\x12!.filedb.v1.CollectionStatsRequest\x1a\".filedb.v1.CollectionStatsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/{collection}/statsB.Z,github.com/srjn45/filedbv2/internal/pb/protob\x06proto3"

var (
	file_proto_filedb_proto_rawDescOnce sync.Once
	file_proto_filedb_proto_rawDescData []byte
)

func file_proto_filedb_proto_rawDescGZIP() []byte {
	file_proto_filedb_proto_rawDescOnce.Do(func() {
		file_proto_filedb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_filedb_proto_rawDesc), len(file_proto_filedb_proto_rawDesc)))
	})
	return file_proto_filedb_proto_rawDescData
}

var file_proto_filedb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_filedb_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_proto_filedb_proto_goTypes = []any{
	(FilterOp)(0),                    // 0: filedb.v1.FilterOp
	(WatchOp)(0),                     // 1: filedb.v1.WatchOp
	(*Record)(nil),                   // 2: filedb.v1.Record
	(*Filter)(nil),                   // 3: filedb.v1.Filter
	(*FieldFilter)(nil),              // 4: filedb.v1.FieldFilter
	(*AndFilter)(nil),                // 5: filedb.v1.AndFilter
	(*OrFilter)(nil),                 // 6: filedb.v1.OrFilter
	(*CreateCollectionRequest)(nil),  // 7: filedb.v1.CreateCollectionRequest
	(*CreateCollectionResponse)(nil), // 8: filedb.v1.CreateCollectionResponse
	(*DropCollectionRequest)(nil),    // 9: filedb.v1.DropCollectionRequest
	(*DropCollectionResponse)(nil),   // 10: filedb.v1.DropCollectionResponse
	(*ListCollectionsRequest)(nil),   // 11: filedb.v1.ListCollectionsRequest
	(*ListCollectionsResponse)(nil),  // 12: filedb.v1.ListCollectionsResponse
	(*InsertRequest)(nil),            // 13: filedb.v1.InsertRequest
	(*InsertResponse)(nil),           // 14: filedb.v1.InsertResponse
	(*InsertManyRequest)(nil),        // 15: filedb.v1.InsertManyRequest
	(*InsertManyResponse)(nil),       // 16: filedb.v1.InsertManyResponse
	(*FindByIdRequest)(nil),          // 17: filedb.v1.FindByIdRequest
	(*FindRequest)(nil),              // 18: filedb.v1.FindRequest
	(*FindResponse)(nil),             // 19: filedb.v1.FindResponse
	(*UpdateRequest)(nil),            // 20: filedb.v1.UpdateRequest
	(*UpdateResponse)(nil),           // 21: filedb.v1.UpdateResponse
	(*DeleteRequest)(nil),            // 22: filedb.v1.DeleteRequest
	(*DeleteResponse)(nil),           // 23: filedb.v1.DeleteResponse
	(*EnsureIndexRequest)(nil),       // 24: filedb.v1.EnsureIndexRequest
	(*EnsureIndexResponse)(nil),      // 25: filedb.v1.EnsureIndexResponse
	(*DropIndexRequest)(nil),         // 26: filedb.v1.DropIndexRequest
	(*DropIndexResponse)(nil),        // 27: filedb.v1.DropIndexResponse
	(*ListIndexesRequest)(nil),       // 28: filedb.v1.ListIndexesRequest
	(*ListIndexesResponse)(nil),      // 29: filedb.v1.ListIndexesResponse
	(*BeginTxRequest)(nil),           // 30: filedb.v1.BeginTxRequest
	(*BeginTxResponse)(nil),          // 31: filedb.v1.BeginTxResponse
	(*CommitTxRequest)(nil),          // 32: filedb.v1.CommitTxRequest
	(*CommitTxResponse)(nil),         // 33: filedb.v1.CommitTxResponse
	(*RollbackTxRequest)(nil),        // 34: filedb.v1.RollbackTxRequest
	(*RollbackTxResponse)(nil),       // 35: filedb.v1.RollbackTxResponse
	(*WatchRequest)(nil),             // 36: filedb.v1.WatchRequest
	(*WatchEvent)(nil),               // 37: filedb.v1.WatchEvent
	(*CollectionStatsRequest)(nil),   // 38: filedb.v1.CollectionStatsRequest
	(*CollectionStatsResponse)(nil),  // 39: filedb.v1.CollectionStatsResponse
	(*structpb.Struct)(nil),          // 40: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),    // 41: google.protobuf.Timestamp
}
var file_proto_filedb_proto_depIdxs = []int32{
	40, // 0: filedb.v1.Record.data:type_name -> google.protobuf.Struct
	41, // 1: filedb.v1.Record.date_added:type_name -> google.protobuf.Timestamp
	41, // 2: filedb.v1.Record.date_modified:type_name -> google.protobuf.Timestamp
	4,  // 3: filedb.v1.Filter.field:type_name -> filedb.v1.FieldFilter
	5,  // 4: filedb.v1.Filter.and:type_name -> filedb.v1.AndFilter
	6,  // 5: filedb.v1.Filter.or:type_name -> filedb.v1.OrFilter
	0,  // 6: filedb.v1.FieldFilter.op:type_name -> filedb.v1.FilterOp
	3,  // 7: filedb.v1.AndFilter.filters:type_name -> filedb.v1.Filter
	3,  // 8: filedb.v1.OrFilter.filters:type_name -> filedb.v1.Filter
	40, // 9: filedb.v1.InsertRequest.data:type_name -> google.protobuf.Struct
	40, // 10: filedb.v1.InsertManyRequest.records:type_name -> google.protobuf.Struct
	3,  // 11: filedb.v1.FindRequest.filter:type_name -> filedb.v1.Filter
	2,  // 12: filedb.v1.FindResponse.record:type_name -> filedb.v1.Record
	40, // 13: filedb.v1.UpdateRequest.data:type_name -> google.protobuf.Struct
	3,  // 14: filedb.v1.WatchRequest.filter:type_name -> filedb.v1.Filter
	1,  // 15: filedb.v1.WatchEvent.op:type_name -> filedb.v1.WatchOp
	2,  // 16: filedb.v1.WatchEvent.record:type_name -> filedb.v1.Record
	41, // 17: filedb.v1.WatchEvent.ts:type_name -> google.protobuf.Timestamp
	7,  // 18: filedb.v1.FileDB.CreateCollection:input_type -> filedb.v1.CreateCollectionRequest
	9,  // 19: filedb.v1.FileDB.DropCollection:input_type -> filedb.v1.DropCollectionRequest
	11, // 20: filedb.v1.FileDB.ListCollections:input_type -> filedb.v1.ListCollectionsRequest
	13, // 21: filedb.v1.FileDB.Insert:input_type -> filedb.v1.InsertRequest
	15, // 22: filedb.v1.FileDB.InsertMany:input_type -> filedb.v1.InsertManyRequest
	17, // 23: filedb.v1.FileDB.FindById:input_type -> filedb.v1.FindByIdRequest
	18, // 24: filedb.v1.FileDB.Find:input_type -> filedb.v1.FindRequest
	20, // 25: filedb.v1.FileDB.Update:input_type -> filedb.v1.UpdateRequest
	22, // 26: filedb.v1.FileDB.Delete:input_type -> filedb.v1.DeleteRequest
	24, // 27: filedb.v1.FileDB.EnsureIndex:input_type -> filedb.v1.EnsureIndexRequest
	26, // 28: filedb.v1.FileDB.DropIndex:input_type -> filedb.v1.DropIndexRequest
	28, // 29: filedb.v1.FileDB.ListIndexes:input_type -> filedb.v1.ListIndexesRequest
	30, // 30: filedb.v1.FileDB.BeginTx:input_type -> filedb.v1.BeginTxRequest
	32, // 31: filedb.v1.FileDB.CommitTx:input_type -> filedb.v1.CommitTxRequest
	34, // 32: filedb.v1.FileDB.RollbackTx:input_type -> filedb.v1.RollbackTxRequest
	36, // 33: filedb.v1.FileDB.Watch:input_type -> filedb.v1.WatchRequest
	38, // 34: filedb.v1.FileDB.CollectionStats:input_type -> filedb.v1.CollectionStatsRequest
	8,  // 35: filedb.v1.FileDB.CreateCollection:output_type -> filedb.v1.CreateCollectionResponse
	10, // 36: filedb.v1.FileDB.DropCollection:output_type -> filedb.v1.DropCollectionResponse
	12, // 37: filedb.v1.FileDB.ListCollections:output_type -> filedb.v1.ListCollectionsResponse
	14, // 38: filedb.v1.FileDB.Insert:output_type -> filedb.v1.InsertResponse
	16, // 39: filedb.v1.FileDB.InsertMany:output_type -> filedb.v1.InsertManyResponse
	19, // 40: filedb.v1.FileDB.FindById:output_type -> filedb.v1.FindResponse
	19, // 41: filedb.v1.FileDB.Find:output_type -> filedb.v1.FindResponse
	21, // 42: filedb.v1.FileDB.Update:output_type -> filedb.v1.UpdateResponse
	23, // 43: filedb.v1.FileDB.Delete:output_type -> filedb.v1.DeleteResponse
	25, // 44: filedb.v1.FileDB.EnsureIndex:output_type -> filedb.v1.EnsureIndexResponse
	27, // 45: filedb.v1.FileDB.DropIndex:output_type -> filedb.v1.DropIndexResponse
	29, // 46: filedb.v1.FileDB.ListIndexes:output_type -> filedb.v1.ListIndexesResponse
	31, // 47: filedb.v1.FileDB.BeginTx:output_type -> filedb.v1.BeginTxResponse
	33, // 48: filedb.v1.FileDB.CommitTx:output_type -> filedb.v1.CommitTxResponse
	35, // 49: filedb.v1.FileDB.RollbackTx:output_type -> filedb.v1.RollbackTxResponse
	37, // 50: filedb.v1.FileDB.Watch:output_type -> filedb.v1.WatchEvent
	39, // 51: filedb.v1.FileDB.CollectionStats:output_type -> filedb.v1.CollectionStatsResponse
	35, // [35:52] is the sub-list for method output_type
	18, // [18:35] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_filedb_proto_init() }
func file_proto_filedb_proto_init() {
	if File_proto_filedb_proto != nil {
		return
	}
	file_proto_filedb_proto_msgTypes[1].OneofWrappers = []any{
		(*Filter_Field)(nil),
		(*Filter_And)(nil),
		(*Filter_Or)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_filedb_proto_rawDesc), len(file_proto_filedb_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_filedb_proto_goTypes,
		DependencyIndexes: file_proto_filedb_proto_depIdxs,
		EnumInfos:         file_proto_filedb_proto_enumTypes,
		MessageInfos:      file_proto_filedb_proto_msgTypes,
	}.Build()
	File_proto_filedb_proto = out.File
	file_proto_filedb_proto_goTypes = nil
	file_proto_filedb_proto_depIdxs = nil
}
