# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: scriva.proto for package 'scriva.v1'

require 'grpc'
require 'scriva/proto/scriva_pb'

module Scriva
  module V1
    module Scriva
      # ---------------------------------------------------------------------------
      # Service
      # ---------------------------------------------------------------------------
      #
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'scriva.v1.Scriva'

        rpc :CreateCollection, ::Scriva::V1::CreateCollectionRequest, ::Scriva::V1::CreateCollectionResponse
        rpc :DropCollection, ::Scriva::V1::DropCollectionRequest, ::Scriva::V1::DropCollectionResponse
        rpc :ListCollections, ::Scriva::V1::ListCollectionsRequest, ::Scriva::V1::ListCollectionsResponse
        # --- CRUD ---
        #
        rpc :Insert, ::Scriva::V1::InsertRequest, ::Scriva::V1::InsertResponse
        rpc :InsertMany, ::Scriva::V1::InsertManyRequest, ::Scriva::V1::InsertManyResponse
        rpc :FindById, ::Scriva::V1::FindByIdRequest, ::Scriva::V1::FindResponse
        # Server-streaming: results are streamed back one by one.
        rpc :Find, ::Scriva::V1::FindRequest, stream(::Scriva::V1::FindResponse)
        rpc :Update, ::Scriva::V1::UpdateRequest, ::Scriva::V1::UpdateResponse
        rpc :Delete, ::Scriva::V1::DeleteRequest, ::Scriva::V1::DeleteResponse
        # --- Keyed CRUD, Upsert & compare-and-swap (N1) ---
        #
        # These map straight onto the embedded engine's keyed operations, giving
        # network clients natural (caller-supplied) string keys, upsert, and
        # optimistic-concurrency updates keyed on a per-record revision (`rev`).
        #
        # Upsert inserts data under key if no live record carries it, or replaces the
        # existing record's data if one does — atomically. Returns the resulting
        # record with its (incremented on replace) revision. This is the keyed-insert
        # path: there is no separate InsertWithKey RPC.
        rpc :Upsert, ::Scriva::V1::UpsertRequest, ::Scriva::V1::UpsertResponse
        # FindByKey returns the record carrying the caller-supplied string key.
        # A missing key yields NOT_FOUND.
        rpc :FindByKey, ::Scriva::V1::FindByKeyRequest, ::Scriva::V1::FindResponse
        # UpdateByKey overwrites the record carrying key, preserving the key itself.
        # A missing key yields NOT_FOUND.
        rpc :UpdateByKey, ::Scriva::V1::UpdateByKeyRequest, ::Scriva::V1::UpdateResponse
        # DeleteByKey removes the record carrying key. A missing key yields NOT_FOUND.
        rpc :DeleteByKey, ::Scriva::V1::DeleteByKeyRequest, ::Scriva::V1::DeleteResponse
        # UpdateIfRev conditionally updates the record carrying key: the write is
        # applied only if the record's current revision equals expected_rev. A stale
        # revision (or a missing key) is a clean no-op reported as swapped=false, not
        # an error.
        rpc :UpdateIfRev, ::Scriva::V1::UpdateIfRevRequest, ::Scriva::V1::UpdateIfRevResponse
        # --- Secondary indexes ---
        #
        rpc :EnsureIndex, ::Scriva::V1::EnsureIndexRequest, ::Scriva::V1::EnsureIndexResponse
        rpc :DropIndex, ::Scriva::V1::DropIndexRequest, ::Scriva::V1::DropIndexResponse
        rpc :ListIndexes, ::Scriva::V1::ListIndexesRequest, ::Scriva::V1::ListIndexesResponse
        # --- Transactions ---
        #
        rpc :BeginTx, ::Scriva::V1::BeginTxRequest, ::Scriva::V1::BeginTxResponse
        rpc :CommitTx, ::Scriva::V1::CommitTxRequest, ::Scriva::V1::CommitTxResponse
        rpc :RollbackTx, ::Scriva::V1::RollbackTxRequest, ::Scriva::V1::RollbackTxResponse
        # --- Watch (server-streaming change feed) ---
        #
        rpc :Watch, ::Scriva::V1::WatchRequest, stream(::Scriva::V1::WatchEvent)
        # --- Aggregations (N4) ---
        #
        # Aggregate computes count and numeric aggregations (sum/avg/min/max) over the
        # live records matching the same Filter as Find, optionally grouped by a field.
        # It server-streams one message per group; a plain (ungrouped) aggregation
        # streams a single message. Aggregation runs entirely in the engine — the
        # collection is never materialised on the client.
        rpc :Aggregate, ::Scriva::V1::AggregateRequest, stream(::Scriva::V1::AggregateResponse)
        # --- Stats ---
        #
        rpc :CollectionStats, ::Scriva::V1::CollectionStatsRequest, ::Scriva::V1::CollectionStatsResponse
        # --- Admin ---
        #
        # Compact runs a forced, synchronous compaction pass on a collection and
        # returns only after it completes.
        rpc :Compact, ::Scriva::V1::CompactRequest, ::Scriva::V1::CompactResponse
        # Snapshot streams a consistent, gzip-compressed tar archive of the whole
        # database. Restore by extracting it into a data directory. gRPC-only:
        # binary streaming does not map cleanly onto the REST gateway.
        rpc :Snapshot, ::Scriva::V1::SnapshotRequest, stream(::Scriva::V1::SnapshotChunk)
        # --- Replication (R1) ---
        #
        # Replicate is the leader's log-shipping feed: a follower tails committed
        # segment entries, each tagged with a monotonic global sequence number (LSN),
        # and applies them through the normal write path to stay consistent. The
        # follower asks to resume from the last LSN it applied (from_lsn); the leader
        # streams every committed entry with lsn > from_lsn — first any recent history
        # still buffered, then live writes as they commit. A follower too far behind
        # for the leader's in-memory buffer gets FAILED_PRECONDITION and must
        # re-bootstrap from a Snapshot. gRPC-only (binary, long-lived stream).
        rpc :Replicate, ::Scriva::V1::ReplicateRequest, stream(::Scriva::V1::ReplicationRecord)
        # ReplicationStatus reports the leader's current LSN and, for each connected
        # follower, the last LSN shipped to it and its lag. Used for observability and
        # to read the leader's LSN watermark before bootstrapping a fresh follower.
        rpc :ReplicationStatus, ::Scriva::V1::ReplicationStatusRequest, ::Scriva::V1::ReplicationStatusResponse
        # --- Failover (R3) ---
        #
        # Promote flips a caught-up follower into a leader: it stops replicating from
        # its upstream, lifts the read-only guard, and begins accepting writes.
        # Promotion is refused with FAILED_PRECONDITION when the node is not a
        # follower, or when its replication lag (last-known leader LSN minus applied
        # LSN) exceeds the server's configured threshold — pass force to override that
        # guard when the leader is unrecoverable and some divergence is acceptable.
        # This is an admin operation and requires a read-write API key. Promotion is a
        # one-way transition; automatic leader election is out of scope.
        rpc :Promote, ::Scriva::V1::PromoteRequest, ::Scriva::V1::PromoteResponse
      end

      Stub = Service.rpc_stub_class
    end
    # --- Collection management ---
  end
end
