<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scriva.proto

namespace Scriva\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * AggregateResponse is one group's result. For a grouped request there is one per
 * distinct group_by value, streamed in ascending group order; for an ungrouped
 * request there is exactly one, carrying a null group_value.
 *
 * Generated from protobuf message <code>scriva.v1.AggregateResponse</code>
 */
class AggregateResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The group_by field's value for this group, type-preserved (number, string,
     * bool). Null for the whole-set group and for records missing the group field.
     *
     * Generated from protobuf field <code>.google.protobuf.Value group_value = 1 [json_name = "groupValue"];</code>
     */
    protected $group_value = null;
    /**
     * Records in this group (post-filter). Always populated.
     *
     * Generated from protobuf field <code>uint64 count = 2 [json_name = "count"];</code>
     */
    protected $count = 0;
    /**
     * Numeric aggregates over `field` across this group's records that carried a
     * numeric value. Meaningful only when `numeric` is true.
     *
     * Generated from protobuf field <code>double sum = 3 [json_name = "sum"];</code>
     */
    protected $sum = 0.0;
    /**
     * Generated from protobuf field <code>double avg = 4 [json_name = "avg"];</code>
     */
    protected $avg = 0.0;
    /**
     * Generated from protobuf field <code>double min = 5 [json_name = "min"];</code>
     */
    protected $min = 0.0;
    /**
     * Generated from protobuf field <code>double max = 6 [json_name = "max"];</code>
     */
    protected $max = 0.0;
    /**
     * numeric is true when at least one record in the group carried a numeric
     * `field`; when false the sum/avg/min/max above are zero and meaningless (e.g.
     * a count-only aggregation, or a group where the field was absent/non-numeric).
     *
     * Generated from protobuf field <code>bool numeric = 7 [json_name = "numeric"];</code>
     */
    protected $numeric = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Value $group_value
     *           The group_by field's value for this group, type-preserved (number, string,
     *           bool). Null for the whole-set group and for records missing the group field.
     *     @type int|string $count
     *           Records in this group (post-filter). Always populated.
     *     @type float $sum
     *           Numeric aggregates over `field` across this group's records that carried a
     *           numeric value. Meaningful only when `numeric` is true.
     *     @type float $avg
     *     @type float $min
     *     @type float $max
     *     @type bool $numeric
     *           numeric is true when at least one record in the group carried a numeric
     *           `field`; when false the sum/avg/min/max above are zero and meaningless (e.g.
     *           a count-only aggregation, or a group where the field was absent/non-numeric).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Scriva::initOnce();
        parent::__construct($data);
    }

    /**
     * The group_by field's value for this group, type-preserved (number, string,
     * bool). Null for the whole-set group and for records missing the group field.
     *
     * Generated from protobuf field <code>.google.protobuf.Value group_value = 1 [json_name = "groupValue"];</code>
     * @return \Google\Protobuf\Value|null
     */
    public function getGroupValue()
    {
        return $this->group_value;
    }

    public function hasGroupValue()
    {
        return isset($this->group_value);
    }

    public function clearGroupValue()
    {
        unset($this->group_value);
    }

    /**
     * The group_by field's value for this group, type-preserved (number, string,
     * bool). Null for the whole-set group and for records missing the group field.
     *
     * Generated from protobuf field <code>.google.protobuf.Value group_value = 1 [json_name = "groupValue"];</code>
     * @param \Google\Protobuf\Value $var
     * @return $this
     */
    public function setGroupValue($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Value::class);
        $this->group_value = $var;

        return $this;
    }

    /**
     * Records in this group (post-filter). Always populated.
     *
     * Generated from protobuf field <code>uint64 count = 2 [json_name = "count"];</code>
     * @return int|string
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Records in this group (post-filter). Always populated.
     *
     * Generated from protobuf field <code>uint64 count = 2 [json_name = "count"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkUint64($var);
        $this->count = $var;

        return $this;
    }

    /**
     * Numeric aggregates over `field` across this group's records that carried a
     * numeric value. Meaningful only when `numeric` is true.
     *
     * Generated from protobuf field <code>double sum = 3 [json_name = "sum"];</code>
     * @return float
     */
    public function getSum()
    {
        return $this->sum;
    }

    /**
     * Numeric aggregates over `field` across this group's records that carried a
     * numeric value. Meaningful only when `numeric` is true.
     *
     * Generated from protobuf field <code>double sum = 3 [json_name = "sum"];</code>
     * @param float $var
     * @return $this
     */
    public function setSum($var)
    {
        GPBUtil::checkDouble($var);
        $this->sum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double avg = 4 [json_name = "avg"];</code>
     * @return float
     */
    public function getAvg()
    {
        return $this->avg;
    }

    /**
     * Generated from protobuf field <code>double avg = 4 [json_name = "avg"];</code>
     * @param float $var
     * @return $this
     */
    public function setAvg($var)
    {
        GPBUtil::checkDouble($var);
        $this->avg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double min = 5 [json_name = "min"];</code>
     * @return float
     */
    public function getMin()
    {
        return $this->min;
    }

    /**
     * Generated from protobuf field <code>double min = 5 [json_name = "min"];</code>
     * @param float $var
     * @return $this
     */
    public function setMin($var)
    {
        GPBUtil::checkDouble($var);
        $this->min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double max = 6 [json_name = "max"];</code>
     * @return float
     */
    public function getMax()
    {
        return $this->max;
    }

    /**
     * Generated from protobuf field <code>double max = 6 [json_name = "max"];</code>
     * @param float $var
     * @return $this
     */
    public function setMax($var)
    {
        GPBUtil::checkDouble($var);
        $this->max = $var;

        return $this;
    }

    /**
     * numeric is true when at least one record in the group carried a numeric
     * `field`; when false the sum/avg/min/max above are zero and meaningless (e.g.
     * a count-only aggregation, or a group where the field was absent/non-numeric).
     *
     * Generated from protobuf field <code>bool numeric = 7 [json_name = "numeric"];</code>
     * @return bool
     */
    public function getNumeric()
    {
        return $this->numeric;
    }

    /**
     * numeric is true when at least one record in the group carried a numeric
     * `field`; when false the sum/avg/min/max above are zero and meaningless (e.g.
     * a count-only aggregation, or a group where the field was absent/non-numeric).
     *
     * Generated from protobuf field <code>bool numeric = 7 [json_name = "numeric"];</code>
     * @param bool $var
     * @return $this
     */
    public function setNumeric($var)
    {
        GPBUtil::checkBool($var);
        $this->numeric = $var;

        return $this;
    }

}

