<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scriva.proto

namespace Scriva\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>scriva.v1.AndFilter</code>
 */
class AndFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .scriva.v1.Filter filters = 1 [json_name = "filters"];</code>
     */
    private $filters;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Scriva\V1\Filter>|\Google\Protobuf\Internal\RepeatedField $filters
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Scriva::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .scriva.v1.Filter filters = 1 [json_name = "filters"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFilters()
    {
        return $this->filters;
    }

    /**
     * Generated from protobuf field <code>repeated .scriva.v1.Filter filters = 1 [json_name = "filters"];</code>
     * @param array<\Scriva\V1\Filter>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFilters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Scriva\V1\Filter::class);
        $this->filters = $arr;

        return $this;
    }

}

