<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scriva.proto

namespace Scriva\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A composable filter node.
 *
 * Generated from protobuf message <code>scriva.v1.Filter</code>
 */
class Filter extends \Google\Protobuf\Internal\Message
{
    protected $kind;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Scriva\V1\FieldFilter $field
     *     @type \Scriva\V1\AndFilter $and
     *     @type \Scriva\V1\OrFilter $or
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Scriva::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.scriva.v1.FieldFilter field = 1 [json_name = "field"];</code>
     * @return \Scriva\V1\FieldFilter|null
     */
    public function getField()
    {
        return $this->readOneof(1);
    }

    public function hasField()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.scriva.v1.FieldFilter field = 1 [json_name = "field"];</code>
     * @param \Scriva\V1\FieldFilter $var
     * @return $this
     */
    public function setField($var)
    {
        GPBUtil::checkMessage($var, \Scriva\V1\FieldFilter::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.scriva.v1.AndFilter and = 2 [json_name = "and"];</code>
     * @return \Scriva\V1\AndFilter|null
     */
    public function getAnd()
    {
        return $this->readOneof(2);
    }

    public function hasAnd()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.scriva.v1.AndFilter and = 2 [json_name = "and"];</code>
     * @param \Scriva\V1\AndFilter $var
     * @return $this
     */
    public function setAnd($var)
    {
        GPBUtil::checkMessage($var, \Scriva\V1\AndFilter::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.scriva.v1.OrFilter or = 3 [json_name = "or"];</code>
     * @return \Scriva\V1\OrFilter|null
     */
    public function getOr()
    {
        return $this->readOneof(3);
    }

    public function hasOr()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.scriva.v1.OrFilter or = 3 [json_name = "or"];</code>
     * @param \Scriva\V1\OrFilter $var
     * @return $this
     */
    public function setOr($var)
    {
        GPBUtil::checkMessage($var, \Scriva\V1\OrFilter::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getKind()
    {
        return $this->whichOneof("kind");
    }

}

