<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scriva.proto

namespace Scriva\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>scriva.v1.FilterOp</code>
 */
class FilterOp
{
    /**
     * Generated from protobuf enum <code>FILTER_OP_UNSPECIFIED = 0;</code>
     */
    const FILTER_OP_UNSPECIFIED = 0;
    /**
     * equal
     *
     * Generated from protobuf enum <code>EQ = 1;</code>
     */
    const EQ = 1;
    /**
     * not equal
     *
     * Generated from protobuf enum <code>NEQ = 2;</code>
     */
    const NEQ = 2;
    /**
     * greater than
     *
     * Generated from protobuf enum <code>GT = 3;</code>
     */
    const GT = 3;
    /**
     * greater than or equal
     *
     * Generated from protobuf enum <code>GTE = 4;</code>
     */
    const GTE = 4;
    /**
     * less than
     *
     * Generated from protobuf enum <code>LT = 5;</code>
     */
    const LT = 5;
    /**
     * less than or equal
     *
     * Generated from protobuf enum <code>LTE = 6;</code>
     */
    const LTE = 6;
    /**
     * string contains
     *
     * Generated from protobuf enum <code>CONTAINS = 7;</code>
     */
    const CONTAINS = 7;
    /**
     * regular expression match
     *
     * Generated from protobuf enum <code>REGEX = 8;</code>
     */
    const REGEX = 8;

    private static $valueToName = [
        self::FILTER_OP_UNSPECIFIED => 'FILTER_OP_UNSPECIFIED',
        self::EQ => 'EQ',
        self::NEQ => 'NEQ',
        self::GT => 'GT',
        self::GTE => 'GTE',
        self::LT => 'LT',
        self::LTE => 'LTE',
        self::CONTAINS => 'CONTAINS',
        self::REGEX => 'REGEX',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

