<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scriva.proto

namespace Scriva\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>scriva.v1.InsertResponse</code>
 */
class InsertResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1 [json_name = "id"];</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string date_added = 2 [json_name = "dateAdded"];</code>
     */
    protected $date_added = '';
    /**
     * Caller-supplied string key (empty for a keyless insert) and the record's
     * revision. A fresh insert always starts at rev 1.
     *
     * Generated from protobuf field <code>string key = 3 [json_name = "key"];</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>uint64 rev = 4 [json_name = "rev"];</code>
     */
    protected $rev = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $date_added
     *     @type string $key
     *           Caller-supplied string key (empty for a keyless insert) and the record's
     *           revision. A fresh insert always starts at rev 1.
     *     @type int|string $rev
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Scriva::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1 [json_name = "id"];</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1 [json_name = "id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string date_added = 2 [json_name = "dateAdded"];</code>
     * @return string
     */
    public function getDateAdded()
    {
        return $this->date_added;
    }

    /**
     * Generated from protobuf field <code>string date_added = 2 [json_name = "dateAdded"];</code>
     * @param string $var
     * @return $this
     */
    public function setDateAdded($var)
    {
        GPBUtil::checkString($var, True);
        $this->date_added = $var;

        return $this;
    }

    /**
     * Caller-supplied string key (empty for a keyless insert) and the record's
     * revision. A fresh insert always starts at rev 1.
     *
     * Generated from protobuf field <code>string key = 3 [json_name = "key"];</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Caller-supplied string key (empty for a keyless insert) and the record's
     * revision. A fresh insert always starts at rev 1.
     *
     * Generated from protobuf field <code>string key = 3 [json_name = "key"];</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 rev = 4 [json_name = "rev"];</code>
     * @return int|string
     */
    public function getRev()
    {
        return $this->rev;
    }

    /**
     * Generated from protobuf field <code>uint64 rev = 4 [json_name = "rev"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setRev($var)
    {
        GPBUtil::checkUint64($var);
        $this->rev = $var;

        return $this;
    }

}

