<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scriva.proto

namespace Scriva\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>scriva.v1.PromoteResponse</code>
 */
class PromoteResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The node's role after the call: "leader" on a successful promotion.
     *
     * Generated from protobuf field <code>string role = 1 [json_name = "role"];</code>
     */
    protected $role = '';
    /**
     * The LSN the promoted leader continues assigning from — its applied watermark
     * at promotion. New writes are tagged with strictly greater LSNs, so a promoted
     * leader never reuses an LSN the old leader already assigned.
     *
     * Generated from protobuf field <code>uint64 lsn = 2 [json_name = "lsn"];</code>
     */
    protected $lsn = 0;
    /**
     * The replication lag (last-known leader LSN minus applied LSN) observed at the
     * moment of promotion. 0 means the follower was fully caught up.
     *
     * Generated from protobuf field <code>uint64 lag = 3 [json_name = "lag"];</code>
     */
    protected $lag = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $role
     *           The node's role after the call: "leader" on a successful promotion.
     *     @type int|string $lsn
     *           The LSN the promoted leader continues assigning from — its applied watermark
     *           at promotion. New writes are tagged with strictly greater LSNs, so a promoted
     *           leader never reuses an LSN the old leader already assigned.
     *     @type int|string $lag
     *           The replication lag (last-known leader LSN minus applied LSN) observed at the
     *           moment of promotion. 0 means the follower was fully caught up.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Scriva::initOnce();
        parent::__construct($data);
    }

    /**
     * The node's role after the call: "leader" on a successful promotion.
     *
     * Generated from protobuf field <code>string role = 1 [json_name = "role"];</code>
     * @return string
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * The node's role after the call: "leader" on a successful promotion.
     *
     * Generated from protobuf field <code>string role = 1 [json_name = "role"];</code>
     * @param string $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkString($var, True);
        $this->role = $var;

        return $this;
    }

    /**
     * The LSN the promoted leader continues assigning from — its applied watermark
     * at promotion. New writes are tagged with strictly greater LSNs, so a promoted
     * leader never reuses an LSN the old leader already assigned.
     *
     * Generated from protobuf field <code>uint64 lsn = 2 [json_name = "lsn"];</code>
     * @return int|string
     */
    public function getLsn()
    {
        return $this->lsn;
    }

    /**
     * The LSN the promoted leader continues assigning from — its applied watermark
     * at promotion. New writes are tagged with strictly greater LSNs, so a promoted
     * leader never reuses an LSN the old leader already assigned.
     *
     * Generated from protobuf field <code>uint64 lsn = 2 [json_name = "lsn"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setLsn($var)
    {
        GPBUtil::checkUint64($var);
        $this->lsn = $var;

        return $this;
    }

    /**
     * The replication lag (last-known leader LSN minus applied LSN) observed at the
     * moment of promotion. 0 means the follower was fully caught up.
     *
     * Generated from protobuf field <code>uint64 lag = 3 [json_name = "lag"];</code>
     * @return int|string
     */
    public function getLag()
    {
        return $this->lag;
    }

    /**
     * The replication lag (last-known leader LSN minus applied LSN) observed at the
     * moment of promotion. 0 means the follower was fully caught up.
     *
     * Generated from protobuf field <code>uint64 lag = 3 [json_name = "lag"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setLag($var)
    {
        GPBUtil::checkUint64($var);
        $this->lag = $var;

        return $this;
    }

}

