<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scriva.proto

namespace Scriva\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>scriva.v1.Record</code>
 */
class Record extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1 [json_name = "id"];</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
     */
    protected $data = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_added = 3 [json_name = "dateAdded"];</code>
     */
    protected $date_added = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_modified = 4 [json_name = "dateModified"];</code>
     */
    protected $date_modified = null;
    /**
     * Caller-supplied string primary key, empty for records inserted without one.
     *
     * Generated from protobuf field <code>string key = 5 [json_name = "key"];</code>
     */
    protected $key = '';
    /**
     * Monotonic per-record revision, bumped on every write. Fresh records start
     * at 1. Feed it to UpdateIfRev for optimistic-concurrency updates.
     *
     * Generated from protobuf field <code>uint64 rev = 6 [json_name = "rev"];</code>
     */
    protected $rev = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type \Google\Protobuf\Struct $data
     *     @type \Google\Protobuf\Timestamp $date_added
     *     @type \Google\Protobuf\Timestamp $date_modified
     *     @type string $key
     *           Caller-supplied string primary key, empty for records inserted without one.
     *     @type int|string $rev
     *           Monotonic per-record revision, bumped on every write. Fresh records start
     *           at 1. Feed it to UpdateIfRev for optimistic-concurrency updates.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Scriva::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1 [json_name = "id"];</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1 [json_name = "id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getData()
    {
        return $this->data;
    }

    public function hasData()
    {
        return isset($this->data);
    }

    public function clearData()
    {
        unset($this->data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_added = 3 [json_name = "dateAdded"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getDateAdded()
    {
        return $this->date_added;
    }

    public function hasDateAdded()
    {
        return isset($this->date_added);
    }

    public function clearDateAdded()
    {
        unset($this->date_added);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_added = 3 [json_name = "dateAdded"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setDateAdded($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->date_added = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_modified = 4 [json_name = "dateModified"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getDateModified()
    {
        return $this->date_modified;
    }

    public function hasDateModified()
    {
        return isset($this->date_modified);
    }

    public function clearDateModified()
    {
        unset($this->date_modified);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_modified = 4 [json_name = "dateModified"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setDateModified($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->date_modified = $var;

        return $this;
    }

    /**
     * Caller-supplied string primary key, empty for records inserted without one.
     *
     * Generated from protobuf field <code>string key = 5 [json_name = "key"];</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Caller-supplied string primary key, empty for records inserted without one.
     *
     * Generated from protobuf field <code>string key = 5 [json_name = "key"];</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Monotonic per-record revision, bumped on every write. Fresh records start
     * at 1. Feed it to UpdateIfRev for optimistic-concurrency updates.
     *
     * Generated from protobuf field <code>uint64 rev = 6 [json_name = "rev"];</code>
     * @return int|string
     */
    public function getRev()
    {
        return $this->rev;
    }

    /**
     * Monotonic per-record revision, bumped on every write. Fresh records start
     * at 1. Feed it to UpdateIfRev for optimistic-concurrency updates.
     *
     * Generated from protobuf field <code>uint64 rev = 6 [json_name = "rev"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setRev($var)
    {
        GPBUtil::checkUint64($var);
        $this->rev = $var;

        return $this;
    }

}

