<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scriva.proto

namespace Scriva\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>scriva.v1.RollbackTxRequest</code>
 */
class RollbackTxRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tx_id = 1 [json_name = "txId"];</code>
     */
    protected $tx_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tx_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Scriva::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tx_id = 1 [json_name = "txId"];</code>
     * @return string
     */
    public function getTxId()
    {
        return $this->tx_id;
    }

    /**
     * Generated from protobuf field <code>string tx_id = 1 [json_name = "txId"];</code>
     * @param string $var
     * @return $this
     */
    public function setTxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->tx_id = $var;

        return $this;
    }

}

