<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scriva.proto

namespace Scriva\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>scriva.v1.UpsertResponse</code>
 */
class UpsertResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The resulting record, including its key and (incremented on replace) rev.
     *
     * Generated from protobuf field <code>.scriva.v1.Record record = 1 [json_name = "record"];</code>
     */
    protected $record = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Scriva\V1\Record $record
     *           The resulting record, including its key and (incremented on replace) rev.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Scriva::initOnce();
        parent::__construct($data);
    }

    /**
     * The resulting record, including its key and (incremented on replace) rev.
     *
     * Generated from protobuf field <code>.scriva.v1.Record record = 1 [json_name = "record"];</code>
     * @return \Scriva\V1\Record|null
     */
    public function getRecord()
    {
        return $this->record;
    }

    public function hasRecord()
    {
        return isset($this->record);
    }

    public function clearRecord()
    {
        unset($this->record);
    }

    /**
     * The resulting record, including its key and (incremented on replace) rev.
     *
     * Generated from protobuf field <code>.scriva.v1.Record record = 1 [json_name = "record"];</code>
     * @param \Scriva\V1\Record $var
     * @return $this
     */
    public function setRecord($var)
    {
        GPBUtil::checkMessage($var, \Scriva\V1\Record::class);
        $this->record = $var;

        return $this;
    }

}

