<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scriva.proto

namespace Scriva\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>scriva.v1.WatchRequest</code>
 */
class WatchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string collection = 1 [json_name = "collection"];</code>
     */
    protected $collection = '';
    /**
     * optional: only receive events matching this filter
     *
     * Generated from protobuf field <code>.scriva.v1.Filter filter = 2 [json_name = "filter"];</code>
     */
    protected $filter = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $collection
     *     @type \Scriva\V1\Filter $filter
     *           optional: only receive events matching this filter
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Scriva::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string collection = 1 [json_name = "collection"];</code>
     * @return string
     */
    public function getCollection()
    {
        return $this->collection;
    }

    /**
     * Generated from protobuf field <code>string collection = 1 [json_name = "collection"];</code>
     * @param string $var
     * @return $this
     */
    public function setCollection($var)
    {
        GPBUtil::checkString($var, True);
        $this->collection = $var;

        return $this;
    }

    /**
     * optional: only receive events matching this filter
     *
     * Generated from protobuf field <code>.scriva.v1.Filter filter = 2 [json_name = "filter"];</code>
     * @return \Scriva\V1\Filter|null
     */
    public function getFilter()
    {
        return $this->filter;
    }

    public function hasFilter()
    {
        return isset($this->filter);
    }

    public function clearFilter()
    {
        unset($this->filter);
    }

    /**
     * optional: only receive events matching this filter
     *
     * Generated from protobuf field <code>.scriva.v1.Filter filter = 2 [json_name = "filter"];</code>
     * @param \Scriva\V1\Filter $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkMessage($var, \Scriva\V1\Filter::class);
        $this->filter = $var;

        return $this;
    }

}

